import type { Module } from './types'

// A1.2 — módulos temáticos (11-19): vocabulário aplicado em situações reais.
// Densos: cada um é um "aulão" com tabelas, diálogos, erros e quiz longo.

export const A12_THEMEN: Module[] = [
  // ═══ 11 · Der Imperativ ═══
  {
    id: 'a12-imperativ',
    level: 'a12',
    num: '11',
    title: 'Der Imperativ',
    subtitle: 'Dar ordens, pedir, aconselhar',
    shape: 'triangle',
    minutes: 25,
    vocabTags: ['verbos', 'frases'],
    sections: [
      { kind: 'text', title: 'Três jeitos de mandar', body: 'O imperativo muda conforme com QUEM você fala: du (informal, 1 pessoa), ihr (informal, várias), Sie (formal). Em todos, o verbo abre a frase — o sujeito some (du/ihr) ou vem depois (Sie).' },
      {
        kind: 'table',
        title: 'Formação',
        head: ['Para', 'Regra', 'machen', 'kommen'],
        rows: [
          ['du', 'radical (sem -st, sem "du")', 'Mach!', 'Komm!'],
          ['ihr', 'forma do ihr (sem "ihr")', 'Macht!', 'Kommt!'],
          ['Sie', 'Infinitiv + Sie', 'Machen Sie!', 'Kommen Sie!'],
        ],
        note: 'Com bitte fica educado: "Kommen Sie bitte herein!"',
      },
      {
        kind: 'table',
        title: 'Irregulares que caem em prova',
        head: ['Verbo', 'du-Imperativ', 'Exemplo'],
        rows: [
          ['sein', 'Sei!', 'Sei ruhig! (Fica quieto!)'],
          ['nehmen', 'Nimm!', 'Nimm den Bus!'],
          ['lesen', 'Lies!', 'Lies das Buch!'],
          ['sprechen', 'Sprich!', 'Sprich lauter!'],
          ['essen', 'Iss!', 'Iss dein Brot!'],
          ['geben', 'Gib!', 'Gib mir das!'],
          ['fahren', 'Fahr!', 'Fahr langsam! (SEM umlaut)'],
        ],
        note: 'Verbos e→i/ie MANTÊM a mudança (Nimm, Lies, Sprich, Iss, Gib). Verbos a→ä PERDEM o umlaut (Fahr, Schlaf).',
      },
      {
        kind: 'table',
        title: 'Suavizadores — o segredo da educação',
        head: ['Palavra', 'Efeito', 'Exemplo'],
        rows: [
          ['bitte', 'por favor', 'Komm bitte!'],
          ['mal', '"aí", relaxa a ordem', 'Warte mal!'],
          ['doch', 'insistência amigável', 'Komm doch mit!'],
          ['mal + bitte', 'super educado', 'Gib mir mal bitte das Salz.'],
        ],
      },
      { kind: 'tip', title: 'Com verbos separáveis', body: 'O prefixo continua indo para o fim: "Steh auf!" (Levanta!), "Ruf mich an!" (Me liga!), "Komm mit!" (Vem junto!), "Mach die Tür zu!" (Fecha a porta!).' },
      {
        kind: 'examples',
        title: 'Ordens úteis do dia a dia',
        items: [
          { de: 'Hör bitte zu!', pt: 'Escuta, por favor!' },
          { de: 'Sprechen Sie bitte langsamer!', pt: 'Fale mais devagar, por favor! (formal)' },
          { de: 'Steh auf! Es ist schon halb neun!', pt: 'Levanta! Já são oito e meia!' },
          { de: 'Macht die Bücher auf!', pt: 'Abram os livros! (para a turma)' },
          { de: 'Nimm doch noch ein Stück Kuchen!', pt: 'Pega mais um pedaço de bolo, vai!' },
          { de: 'Sei bitte pünktlich!', pt: 'Seja pontual, por favor!' },
        ],
      },
      {
        kind: 'dialog',
        title: 'Dialog — Im Deutschkurs',
        lines: [
          { who: 'Lena', de: 'Der Lehrer sagt immer: „Sprich lauter!"', pt: 'O professor sempre diz: "Fale mais alto!"' },
          { who: 'Paulo', de: 'Bei mir sagt er: „Lies den Text und mach die Übung!"', pt: 'Comigo ele diz: "Leia o texto e faça o exercício!"' },
          { who: 'Lena', de: 'Hör mal, hilfst du mir mit der Hausaufgabe?', pt: 'Escuta, você me ajuda com a lição?' },
          { who: 'Paulo', de: 'Klar. Komm doch nach dem Kurs zu mir.', pt: 'Claro. Vem lá em casa depois do curso.' },
          { who: 'Lena', de: 'Super. Ruf mich vorher an, ja?', pt: 'Ótimo. Me liga antes, tá?' },
          { who: 'Paulo', de: 'Mach ich! Und sei bitte pünktlich diesmal.', pt: 'Faço sim! E seja pontual dessa vez, por favor.' },
        ],
      },
      {
        kind: 'fehler',
        title: 'Erros clássicos de brasileiros',
        pairs: [
          { falsch: 'Du komm hier!', richtig: 'Komm hier!', why: 'Imperativo du NÃO leva o pronome "du".' },
          { falsch: 'Fähr langsam!', richtig: 'Fahr langsam!', why: 'a→ä PERDE o umlaut no imperativo.' },
          { falsch: 'Nehm den Bus!', richtig: 'Nimm den Bus!', why: 'e→i mantém: Nimm.' },
          { falsch: 'Sprechen langsamer! (querendo formal)', richtig: 'Sprechen Sie langsamer!', why: 'Formal precisa do "Sie".' },
        ],
      },
      { kind: 'tip', title: 'Método', body: 'Anote 5 ordens que você OUVE (professor, receita, placa) e refaça nas 3 formas du/ihr/Sie. O imperativo se aprende repetindo o que já circula à sua volta.' },
    ],
    quiz: [
      { kind: 'gap', before: '', after: ' langsam! (fahren, du)', answer: ['Fahr'] },
      { kind: 'gap', before: '', after: ' das Buch! (lesen, du)', answer: ['Lies'] },
      { kind: 'gap', before: '', after: ' ruhig! (sein, du)', answer: ['Sei'] },
      { kind: 'choice', prompt: '"Venham aqui!" (amigos, plural):', options: ['Komm her!', 'Kommt her!', 'Kommen Sie her!', 'Kommst her!'], answer: 1 },
      { kind: 'order', words: ['Ruf', 'mich', 'bitte', 'an'], answer: 'Ruf mich bitte an', hint: 'separável: prefixo no fim' },
      { kind: 'choice', prompt: 'Imperativo formal (Sie) de "nehmen":', options: ['Nimm Sie!', 'Nehmt Sie!', 'Nehmen Sie!', 'Nimmst Sie!'], answer: 2 },
      { kind: 'gap', before: '', after: ' mir das Salz! (geben, du)', answer: ['Gib'] },
      { kind: 'choice', prompt: 'O que "doch" faz em "Komm doch mit!"?', options: ['Torna uma pergunta', 'Insistência amigável', 'Nega a ordem', 'Torna formal'], answer: 1 },
      { kind: 'gap', before: 'Steh ', after: '! Es ist spät! (aufstehen, du)', answer: ['auf'] },
      { kind: 'order', words: ['Macht', 'die', 'Bücher', 'auf'], answer: 'Macht die Bücher auf', hint: 'ihr, separável' },
    ],
  },

  // ═══ 12 · Die Farben & Beschreibung ═══
  {
    id: 'a12-farben',
    level: 'a12',
    num: '12',
    title: 'Die Farben & Beschreibung',
    subtitle: 'Cores e descrição — direto da aula 11',
    shape: 'square',
    minutes: 20,
    vocabTags: ['cores', 'adjektive'],
    sections: [
      { kind: 'text', title: 'A ideia', body: 'Cores servem para descrever tudo — roupas, objetos, gostos. Além da lista, há uma regra fina: cor como ADJETIVO fica minúscula; como SUBSTANTIVO (a cor em si), maiúscula.' },
      {
        kind: 'table',
        title: 'A paleta (aula DEUTSCHUNTERRICHT 11)',
        head: ['Alemão', 'Português'],
        rows: [
          ['rot', 'vermelho'], ['blau', 'azul'], ['gelb', 'amarelo'], ['grün', 'verde'],
          ['schwarz', 'preto'], ['weiß', 'branco'], ['grau', 'cinza'], ['braun', 'marrom'],
          ['rosa', 'rosa'], ['lila / violett', 'roxo / lilás'], ['orange', 'laranja'],
          ['beige', 'bege'], ['pink', 'pink (rosa forte)'], ['bunt', 'colorido'],
        ],
      },
      {
        kind: 'table',
        title: 'Intensidade',
        head: ['Prefixo', 'Efeito', 'Exemplo'],
        rows: [
          ['hell-', 'claro', 'hellblau (azul-claro)'],
          ['dunkel-', 'escuro', 'dunkelgrün (verde-escuro)'],
        ],
      },
      { kind: 'tip', title: 'As 4 cores que NÃO declinam', body: 'rosa, lila, orange e beige nunca ganham terminação: "die rosa Blume", "ein lila Kleid" (nunca "rosane"). As outras cores declinam como adjetivo normal: "das rote Auto".' },
      { kind: 'tip', title: 'Adjetivo vs. substantivo', body: 'Adjetivo (minúscula): Das Auto ist rot. Substantivo/nome da cor (maiúscula): Meine Lieblingsfarbe ist Rot. / Ich mag Blau.' },
      {
        kind: 'examples',
        title: 'Frases-modelo',
        items: [
          { de: 'Was ist deine Lieblingsfarbe?', pt: 'Qual é a sua cor favorita?' },
          { de: 'Meine Lieblingsfarbe ist Blau.', pt: 'Minha cor favorita é azul.' },
          { de: 'Der Regenbogen ist bunt.', pt: 'O arco-íris é colorido.' },
          { de: 'Ich trage ein dunkelblaues Hemd.', pt: 'Estou usando uma camisa azul-escura.' },
          { de: 'Welche Farbe hat dein Auto? — Es ist rot.', pt: 'Que cor tem seu carro? — É vermelho.' },
          { de: 'Die rosa Blume gefällt mir.', pt: 'Gosto da flor rosa.' },
        ],
      },
      {
        kind: 'dialog',
        title: 'Dialog — Welche Farbe?',
        lines: [
          { who: 'Lena', de: 'Welche Farbe hat dein neues Auto?', pt: 'Que cor tem seu carro novo?' },
          { who: 'Paulo', de: 'Es ist dunkelgrau. Grau ist praktisch.', pt: 'É cinza-escuro. Cinza é prático.' },
          { who: 'Lena', de: 'Grau? Langweilig! Meine Lieblingsfarbe ist Rot.', pt: 'Cinza? Que sem graça! Minha cor favorita é vermelho.' },
          { who: 'Paulo', de: 'Rot ist zu auffällig für ein Auto.', pt: 'Vermelho é chamativo demais para um carro.' },
          { who: 'Lena', de: 'Und dein Hemd heute? Das ist doch hellblau, oder?', pt: 'E sua camisa hoje? É azul-clara, né?' },
          { who: 'Paulo', de: 'Genau. Hellblau steht mir gut, sagt meine Mutter.', pt: 'Exato. Azul-claro fica bem em mim, diz minha mãe.' },
        ],
      },
      {
        kind: 'fehler',
        title: 'Erros clássicos de brasileiros',
        pairs: [
          { falsch: 'ein rosanes Kleid', richtig: 'ein rosa Kleid', why: 'rosa não declina.' },
          { falsch: 'Meine Lieblingsfarbe ist blau. (minúscula)', richtig: 'Meine Lieblingsfarbe ist Blau.', why: 'Aqui a cor é substantivo → maiúscula.' },
          { falsch: 'Das Auto ist Rot.', richtig: 'Das Auto ist rot.', why: 'Aqui é adjetivo → minúscula.' },
        ],
      },
      { kind: 'tip', title: 'Método', body: 'Olhe ao redor agora e nomeie 5 objetos com cor + artigo ("das weiße Blatt, der schwarze Stift…"). Cores fixam melhor coladas a objetos reais.' },
    ],
    quiz: [
      { kind: 'choice', prompt: '"verde" =', options: ['gelb', 'grün', 'grau', 'braun'], answer: 1 },
      { kind: 'choice', prompt: '"weiß" =', options: ['preto', 'cinza', 'branco', 'bege'], answer: 2 },
      { kind: 'gap', before: 'Meine ', after: ' ist Rot. (cor favorita)', answer: ['Lieblingsfarbe'] },
      { kind: 'choice', prompt: 'O arco-íris é…', options: ['grau', 'bunt', 'beige', 'schwarz'], answer: 1 },
      { kind: 'choice', prompt: 'Qual NÃO declina?', options: ['rot', 'blau', 'rosa', 'grün'], answer: 2 },
      { kind: 'gap', before: 'Ich trage ein ', after: ' Hemd. (azul-escuro)', answer: ['dunkelblaues', 'dunkelblaue'] },
      { kind: 'choice', prompt: '"azul-claro" =', options: ['dunkelblau', 'hellblau', 'blaugrau', 'blaulicht'], answer: 1 },
      { kind: 'choice', prompt: 'Frase correta:', options: ['Das Auto ist Rot.', 'Das Auto ist rot.', 'Das auto ist rot.', 'Das Auto ist die rot.'], answer: 1 },
    ],
  },

  // ═══ 13 · Essen & Trinken + im Restaurant ═══
  {
    id: 'a12-essen',
    level: 'a12',
    num: '13',
    title: 'Essen & im Restaurant',
    subtitle: 'Comida, bebida e pedir no restaurante',
    shape: 'circle',
    minutes: 35,
    vocabTags: ['comida', 'frases'],
    sections: [
      { kind: 'text', title: 'A ideia', body: 'Comer é sobrevivência e cultura. Aqui vêm as refeições, os grupos de alimentos com artigo, e o roteiro completo de um restaurante — do "die Speisekarte, bitte" ao "Zahlen, bitte!".' },
      {
        kind: 'table',
        title: 'As refeições',
        head: ['Alemão', 'Português', 'Quando'],
        rows: [
          ['das Frühstück', 'café da manhã', 'morgens'],
          ['das Mittagessen', 'almoço', 'mittags'],
          ['das Abendessen', 'jantar', 'abends'],
          ['der Snack / der Imbiss', 'lanche', 'zwischendurch'],
        ],
        note: 'Verbos: frühstücken (tomar café), zu Mittag/Abend essen (almoçar/jantar).',
      },
      {
        kind: 'table',
        title: 'Obst & Gemüse (frutas e legumes)',
        head: ['Alemão', 'Português'],
        rows: [
          ['der Apfel', 'maçã'], ['die Banane', 'banana'], ['die Orange', 'laranja'],
          ['die Erdbeere', 'morango'], ['die Kartoffel', 'batata'], ['die Tomate', 'tomate'],
          ['der Salat', 'salada/alface'], ['die Zwiebel', 'cebola'], ['die Karotte', 'cenoura'],
        ],
      },
      {
        kind: 'table',
        title: 'Grundnahrung & Getränke',
        head: ['Alemão', 'Português'],
        rows: [
          ['das Brot', 'pão'], ['der Käse', 'queijo'], ['das Ei', 'ovo'],
          ['das Fleisch', 'carne'], ['der Fisch', 'peixe'], ['der Reis', 'arroz'],
          ['die Nudeln (Pl.)', 'macarrão'], ['das Wasser', 'água'], ['der Kaffee', 'café'],
          ['der Tee', 'chá'], ['der Saft', 'suco'], ['das Bier', 'cerveja'], ['der Wein', 'vinho'],
        ],
      },
      {
        kind: 'table',
        title: 'No restaurante — as frases',
        head: ['Momento', 'Frase', 'Tradução'],
        rows: [
          ['pedir cardápio', 'Die Speisekarte, bitte.', 'O cardápio, por favor.'],
          ['pedir prato', 'Ich hätte gern die Suppe.', 'Eu queria a sopa.'],
          ['pedir (alt.)', 'Ich nehme das Schnitzel.', 'Vou querer o schnitzel.'],
          ['garçom pergunta', 'Und zu trinken?', 'E para beber?'],
          ['pedir conta', 'Zahlen, bitte!', 'A conta, por favor!'],
          ['junto ou separado', 'Zusammen oder getrennt?', 'Junto ou separado?'],
          ['gorjeta', 'Stimmt so.', 'Pode ficar com o troco.'],
        ],
      },
      { kind: 'tip', title: 'schmecken + Dativ', body: 'Para dizer que algo é gostoso: "Das schmeckt mir" (isso me agrada / está gostoso). No restaurante o garçom pergunta: "Schmeckt es Ihnen?" — responda "Ja, sehr gut, danke!". Sabores: süß, sauer, salzig, scharf, lecker.' },
      {
        kind: 'examples',
        title: 'Frases-modelo',
        items: [
          { de: 'Ich hätte gern einen Kaffee und ein Stück Kuchen.', pt: 'Eu queria um café e um pedaço de bolo.' },
          { de: 'Was können Sie empfehlen?', pt: 'O que o senhor recomenda?' },
          { de: 'Guten Appetit!', pt: 'Bom apetite!' },
          { de: 'Die Suppe schmeckt mir sehr gut.', pt: 'A sopa está muito gostosa (me agrada).' },
          { de: 'Zahlen, bitte! Zusammen.', pt: 'A conta, por favor! Junto.' },
          { de: 'Ein Bier vom Fass, bitte.', pt: 'Uma cerveja de chope, por favor.' },
        ],
      },
      {
        kind: 'dialog',
        title: 'Dialog — Im Restaurant',
        lines: [
          { who: 'Kellner', de: 'Guten Abend! Möchten Sie schon bestellen?', pt: 'Boa noite! Já querem pedir?' },
          { who: 'Paulo', de: 'Ja. Ich hätte gern das Schnitzel mit Pommes.', pt: 'Sim. Eu queria o schnitzel com batata frita.' },
          { who: 'Lena', de: 'Und für mich die Gemüsesuppe, bitte.', pt: 'E para mim a sopa de legumes, por favor.' },
          { who: 'Kellner', de: 'Gern. Und zu trinken?', pt: 'Com prazer. E para beber?' },
          { who: 'Paulo', de: 'Ein Bier für mich und ein Wasser für sie.', pt: 'Uma cerveja para mim e uma água para ela.' },
          { who: 'Kellner', de: '(später) Hat es geschmeckt?', pt: '(mais tarde) Estava bom?' },
          { who: 'Lena', de: 'Ja, sehr lecker! Wir möchten zahlen, bitte.', pt: 'Sim, delicioso! Queremos pagar, por favor.' },
          { who: 'Kellner', de: 'Zusammen oder getrennt?', pt: 'Junto ou separado?' },
        ],
      },
      {
        kind: 'fehler',
        title: 'Erros clássicos de brasileiros',
        pairs: [
          { falsch: 'Ich will die Suppe.', richtig: 'Ich hätte gern die Suppe.', why: '"Ich will" soa grosseiro; use "Ich hätte gern" ou "Ich nehme".' },
          { falsch: 'Das schmeckt mich.', richtig: 'Das schmeckt mir.', why: 'schmecken pede Dativo.' },
          { falsch: 'Die Rechnung, bitte geben.', richtig: 'Zahlen, bitte!', why: 'Fórmula fixa para pedir a conta.' },
          { falsch: 'Ich bin fertig → Fertig! (chamando garçom)', richtig: 'Entschuldigung!', why: 'Chama-se o garçom com "Entschuldigung", não "Fertig".' },
        ],
      },
      { kind: 'tip', title: 'Método', body: 'Simule um pedido inteiro em voz alta: entrar → pedir cardápio → escolher prato + bebida → elogiar → pedir a conta. Encene as duas vozes (você e o garçom).' },
    ],
    quiz: [
      { kind: 'choice', prompt: 'Pedir educadamente:', options: ['Ich will Suppe.', 'Ich hätte gern Suppe.', 'Gib mir Suppe.', 'Suppe!'], answer: 1 },
      { kind: 'gap', before: 'Das ', after: ' mir sehr gut. (schmecken — a mim)', answer: ['schmeckt'] },
      { kind: 'choice', prompt: '"A conta, por favor!" =', options: ['Rechnung geben!', 'Zahlen, bitte!', 'Geld, bitte!', 'Ende, bitte!'], answer: 1 },
      { kind: 'choice', prompt: 'Qual é uma bebida?', options: ['der Käse', 'der Saft', 'das Ei', 'der Reis'], answer: 1 },
      { kind: 'gap', before: 'Guten ', after: '! (antes de comer)', answer: ['Appetit'] },
      { kind: 'choice', prompt: '"das Frühstück" é…', options: ['almoço', 'jantar', 'café da manhã', 'lanche'], answer: 2 },
      { kind: 'gap', before: 'Das schmeckt ', after: ' gut. (a mim)', answer: ['mir'] },
      { kind: 'choice', prompt: 'Garçom: "Zusammen oder getrennt?" pergunta sobre…', options: ['a comida', 'o pagamento', 'a bebida', 'a mesa'], answer: 1 },
      { kind: 'order', words: ['Ich', 'hätte', 'gern', 'einen', 'Kaffee'], answer: 'Ich hätte gern einen Kaffee' },
      { kind: 'choice', prompt: '"lecker" significa…', options: ['caro', 'quente', 'gostoso', 'salgado'], answer: 2 },
    ],
  },

  // ═══ 14 · Einkaufen & Kleidung ═══
  {
    id: 'a12-einkaufen',
    level: 'a12',
    num: '14',
    title: 'Einkaufen & Kleidung',
    subtitle: 'Comprar roupa — preço, tamanho, provar',
    shape: 'half',
    minutes: 30,
    vocabTags: ['kleidung', 'frases'],
    sections: [
      { kind: 'text', title: 'A ideia', body: 'Comprar roupa junta vocabulário (as peças, com artigo!), preço, tamanho e três verbos de Dativo que confundem: passen (servir), stehen (ficar bem) e gefallen (agradar).' },
      {
        kind: 'table',
        title: 'A roupa (die Kleidung)',
        head: ['Alemão', 'Português', 'Plural'],
        rows: [
          ['der Pullover', 'suéter', 'die Pullover'],
          ['die Hose', 'calça', 'die Hosen'],
          ['das Hemd', 'camisa', 'die Hemden'],
          ['das T-Shirt', 'camiseta', 'die T-Shirts'],
          ['der Rock', 'saia', 'die Röcke'],
          ['das Kleid', 'vestido', 'die Kleider'],
          ['die Jacke', 'jaqueta', 'die Jacken'],
          ['der Mantel', 'casaco', 'die Mäntel'],
          ['der Schuh', 'sapato', 'die Schuhe'],
          ['die Socke', 'meia', 'die Socken'],
        ],
        note: 'Roupa vem muito no plural: die Schuhe, die Socken. "Ich brauche neue Schuhe."',
      },
      {
        kind: 'table',
        title: 'As frases da loja',
        head: ['Função', 'Frase', 'Tradução'],
        rows: [
          ['perguntar preço', 'Wie viel kostet das?', 'Quanto custa?'],
          ['achar caro', 'Das ist zu teuer.', 'É caro demais.'],
          ['achar barato', 'Das ist günstig.', 'É em conta.'],
          ['tamanho', 'Welche Größe haben Sie?', 'Que tamanho o senhor tem?'],
          ['provar', 'Kann ich das anprobieren?', 'Posso experimentar?'],
          ['pagar', 'Bar oder mit Karte?', 'Dinheiro ou cartão?'],
        ],
      },
      {
        kind: 'table',
        title: 'Os 3 verbos de Dativo da roupa',
        head: ['Verbo', 'Sentido', 'Exemplo'],
        rows: [
          ['passen', 'servir (tamanho)', 'Die Hose passt mir.'],
          ['stehen', 'ficar bem (visual)', 'Das Kleid steht dir gut.'],
          ['gefallen', 'agradar (gosto)', 'Der Mantel gefällt mir.'],
        ],
        note: 'Os três pedem Dativo: mir, dir, ihm… "Die Schuhe passen mir und gefallen mir!"',
      },
      { kind: 'tip', title: 'passen vs. stehen', body: 'passen = questão de TAMANHO (cabe?). stehen = questão de APARÊNCIA (fica bonito?). Uma calça pode passen (servir) mas não stehen (não ficar bem). Ambos + Dativo.' },
      {
        kind: 'examples',
        title: 'Frases-modelo',
        items: [
          { de: 'Wie viel kostet dieser Pullover?', pt: 'Quanto custa este suéter?' },
          { de: 'Haben Sie das auch in Größe M?', pt: 'Tem isso também no tamanho M?' },
          { de: 'Die Jacke passt mir nicht, sie ist zu klein.', pt: 'A jaqueta não me serve, é pequena demais.' },
          { de: 'Das Kleid steht dir super!', pt: 'O vestido fica ótimo em você!' },
          { de: 'Ich nehme die Schuhe. Mit Karte, bitte.', pt: 'Vou levar os sapatos. Com cartão, por favor.' },
          { de: 'Kann ich die Hose anprobieren?', pt: 'Posso provar a calça?' },
        ],
      },
      {
        kind: 'dialog',
        title: 'Dialog — Im Kaufhaus',
        lines: [
          { who: 'Verkäuferin', de: 'Kann ich Ihnen helfen?', pt: 'Posso ajudar?' },
          { who: 'Lena', de: 'Ja, ich suche ein Kleid für eine Party.', pt: 'Sim, procuro um vestido para uma festa.' },
          { who: 'Verkäuferin', de: 'Welche Größe haben Sie?', pt: 'Que tamanho a senhora tem?' },
          { who: 'Lena', de: 'Größe 38. Kann ich das rote anprobieren?', pt: 'Tamanho 38. Posso provar o vermelho?' },
          { who: 'Verkäuferin', de: 'Natürlich. Die Kabine ist da hinten.', pt: 'Claro. O provador é lá atrás.' },
          { who: 'Lena', de: 'Es passt und gefällt mir! Wie viel kostet es?', pt: 'Serve e eu gostei! Quanto custa?' },
          { who: 'Verkäuferin', de: '49 Euro. Zahlen Sie bar oder mit Karte?', pt: '49 euros. Paga em dinheiro ou cartão?' },
          { who: 'Lena', de: 'Mit Karte, bitte.', pt: 'Com cartão, por favor.' },
        ],
      },
      {
        kind: 'fehler',
        title: 'Erros clássicos de brasileiros',
        pairs: [
          { falsch: 'Die Hose passt mich.', richtig: 'Die Hose passt mir.', why: 'passen pede Dativo.' },
          { falsch: 'Das Kleid steht dich gut.', richtig: 'Das Kleid steht dir gut.', why: 'stehen (ficar bem) pede Dativo.' },
          { falsch: 'Wie viel kostet die Schuhe?', richtig: 'Wie viel kosten die Schuhe?', why: 'Schuhe é plural → kosten.' },
          { falsch: 'Ich will diese Hose probieren.', richtig: 'Ich möchte diese Hose anprobieren.', why: 'anprobieren (separável) para roupa; "probieren" é para comida.' },
        ],
      },
      { kind: 'tip', title: 'Método', body: 'Descreva a roupa que você está usando AGORA com artigo, cor e um verbo de Dativo ("Mein blauer Pullover gefällt mir und passt mir gut"). Junta 3 tópicos de uma vez.' },
    ],
    quiz: [
      { kind: 'gap', before: 'Die Hose ', after: ' mir nicht. (servir)', answer: ['passt'] },
      { kind: 'gap', before: 'Das Kleid steht ', after: ' gut. (a você)', answer: ['dir'] },
      { kind: 'choice', prompt: '"Quanto custam os sapatos?" =', options: ['Wie viel kostet die Schuhe?', 'Wie viel kosten die Schuhe?', 'Wie viel Schuhe kostet?', 'Was kostet Schuhe?'], answer: 1 },
      { kind: 'choice', prompt: 'Provar uma roupa =', options: ['probieren', 'anprobieren', 'ausprobieren', 'versuchen'], answer: 1 },
      { kind: 'gap', before: 'Der Mantel ', after: ' mir sehr. (agradar)', answer: ['gefällt'] },
      { kind: 'choice', prompt: '"das Kleid" é…', options: ['a saia', 'o vestido', 'a jaqueta', 'a camisa'], answer: 1 },
      { kind: 'choice', prompt: 'passen se refere a…', options: ['aparência', 'tamanho/caber', 'preço', 'cor'], answer: 1 },
      { kind: 'gap', before: 'Welche ', after: ' haben Sie? (tamanho)', answer: ['Größe'] },
      { kind: 'order', words: ['Kann', 'ich', 'das', 'anprobieren', '?'], answer: 'Kann ich das anprobieren ?' },
      { kind: 'choice', prompt: '"zu teuer" =', options: ['muito barato', 'caro demais', 'em conta', 'de graça'], answer: 1 },
    ],
  },

  // ═══ 15 · Wohnung & Möbel ═══
  {
    id: 'a12-wohnung',
    level: 'a12',
    num: '15',
    title: 'Wohnung & Möbel',
    subtitle: 'A casa, os cômodos, os móveis',
    shape: 'square',
    minutes: 30,
    vocabTags: ['wohnung'],
    sections: [
      { kind: 'text', title: 'A ideia', body: 'Descrever onde e como você mora é tema garantido de A1. Aqui vêm os cômodos, os móveis (com artigo), o anúncio imobiliário decifrado e a descrição de posições com as Wechselpräpositionen.' },
      {
        kind: 'table',
        title: 'Os cômodos (die Zimmer)',
        head: ['Alemão', 'Português'],
        rows: [
          ['das Wohnzimmer', 'sala de estar'],
          ['das Schlafzimmer', 'quarto'],
          ['die Küche', 'cozinha'],
          ['das Bad(ezimmer)', 'banheiro'],
          ['der Flur', 'corredor/hall'],
          ['der Balkon', 'varanda'],
          ['die Garage', 'garagem'],
          ['der Keller', 'porão'],
        ],
      },
      {
        kind: 'table',
        title: 'Os móveis (die Möbel)',
        head: ['Alemão', 'Português'],
        rows: [
          ['das Sofa', 'sofá'], ['das Bett', 'cama'], ['der Tisch', 'mesa'],
          ['der Stuhl', 'cadeira'], ['der Schrank', 'armário'], ['das Regal', 'estante'],
          ['der Kühlschrank', 'geladeira'], ['der Herd', 'fogão'], ['die Lampe', 'luminária'],
          ['der Teppich', 'tapete'], ['der Spiegel', 'espelho'], ['die Waschmaschine', 'máquina de lavar'],
        ],
      },
      {
        kind: 'table',
        title: 'O anúncio imobiliário decifrado',
        head: ['Abreviação', 'Significa', 'Português'],
        rows: [
          ['3-Zi-Wohnung', 'Drei-Zimmer-Wohnung', 'apê de 3 cômodos'],
          ['75 m²', 'fünfundsiebzig Quadratmeter', '75 metros quadrados'],
          ['die Miete', 'aluguel', 'aluguel (base)'],
          ['die Nebenkosten (NK)', 'custos extras', 'condomínio/água/luz'],
          ['warm / kalt', 'com/sem extras', 'aluguel total / só a base'],
          ['die Kaution', 'caução', 'depósito de garantia'],
        ],
      },
      { kind: 'tip', title: 'wohnen + in + Dativo', body: 'Onde você mora usa Dativo: "Ich wohne in einer Wohnung / in einem Haus / im dritten Stock." Descrever o que TEM: es gibt + Akkusativ: "Es gibt einen Balkon und eine große Küche."' },
      {
        kind: 'examples',
        title: 'Frases-modelo',
        items: [
          { de: 'Ich wohne in einer kleinen Wohnung in Berlin.', pt: 'Moro num apartamento pequeno em Berlim.' },
          { de: 'Die Wohnung hat drei Zimmer und einen Balkon.', pt: 'O apartamento tem três cômodos e uma varanda.' },
          { de: 'Das Sofa steht im Wohnzimmer, an der Wand.', pt: 'O sofá fica na sala, junto à parede.' },
          { de: 'In der Küche gibt es einen neuen Kühlschrank.', pt: 'Na cozinha há uma geladeira nova.' },
          { de: 'Die Miete ist 800 Euro warm.', pt: 'O aluguel é 800 euros com tudo incluído.' },
          { de: 'Mein Zimmer ist hell und gemütlich.', pt: 'Meu quarto é claro e aconchegante.' },
        ],
      },
      {
        kind: 'dialog',
        title: 'Dialog — Die neue Wohnung',
        lines: [
          { who: 'Lena', de: 'Wie ist deine neue Wohnung?', pt: 'Como é seu apartamento novo?' },
          { who: 'Paulo', de: 'Toll! Sie hat zwei Zimmer, eine Küche und ein Bad.', pt: 'Ótimo! Tem dois cômodos, cozinha e banheiro.' },
          { who: 'Lena', de: 'Gibt es auch einen Balkon?', pt: 'Tem varanda também?' },
          { who: 'Paulo', de: 'Ja, ein kleiner Balkon. Da steht mein Tisch.', pt: 'Sim, uma varandinha. É onde fica minha mesa.' },
          { who: 'Lena', de: 'Und wie viel ist die Miete?', pt: 'E quanto é o aluguel?' },
          { who: 'Paulo', de: '650 Euro kalt, plus Nebenkosten.', pt: '650 euros a base, mais os custos extras.' },
          { who: 'Lena', de: 'Wo steht dein Bett?', pt: 'Onde fica sua cama?' },
          { who: 'Paulo', de: 'Im Schlafzimmer, neben dem Fenster.', pt: 'No quarto, ao lado da janela.' },
        ],
      },
      {
        kind: 'fehler',
        title: 'Erros clássicos de brasileiros',
        pairs: [
          { falsch: 'Ich wohne in eine Wohnung.', richtig: 'Ich wohne in einer Wohnung.', why: 'wohnen in = posição → Dativo (einer).' },
          { falsch: 'Es gibt ein Balkon.', richtig: 'Es gibt einen Balkon.', why: 'es gibt pede Akkusativ (Balkon masc → einen).' },
          { falsch: 'das Küche', richtig: 'die Küche', why: 'Küche é feminino.' },
          { falsch: 'Die Miete ist 800 Euro heiß.', richtig: 'Die Miete ist 800 Euro warm.', why: 'Aluguel com extras = warm, não heiß.' },
        ],
      },
      { kind: 'tip', title: 'Método', body: 'Faça um tour falado da SUA casa, cômodo por cômodo, dizendo onde cada móvel está (Wechselpräp. + Dativo). Descrição de casa treina móveis + preposições juntos.' },
    ],
    quiz: [
      { kind: 'gap', before: 'Ich wohne in ', after: ' Wohnung. (uma — Dativo)', answer: ['einer'] },
      { kind: 'gap', before: 'Es gibt ', after: ' Balkon. (um — Akkusativ)', answer: ['einen'] },
      { kind: 'choice', prompt: '"a cozinha" =', options: ['der Küche', 'die Küche', 'das Küche', 'die Küchen'], answer: 1 },
      { kind: 'choice', prompt: 'Onde se dorme?', options: ['das Wohnzimmer', 'die Küche', 'das Schlafzimmer', 'der Flur'], answer: 2 },
      { kind: 'choice', prompt: '"der Kühlschrank" é…', options: ['fogão', 'geladeira', 'armário', 'estante'], answer: 1 },
      { kind: 'gap', before: 'Das Sofa steht ', after: ' Wohnzimmer. (no — Dativo)', answer: ['im'] },
      { kind: 'choice', prompt: 'Miete "warm" significa…', options: ['aluguel só a base', 'aluguel com extras incluídos', 'aluguel de verão', 'aluguel caro'], answer: 1 },
      { kind: 'gap', before: 'In der Küche gibt es ', after: ' Herd. (um — Akk, der Herd)', answer: ['einen'] },
      { kind: 'order', words: ['Die', 'Wohnung', 'hat', 'drei', 'Zimmer'], answer: 'Die Wohnung hat drei Zimmer' },
      { kind: 'choice', prompt: '"gemütlich" significa…', options: ['grande', 'caro', 'aconchegante', 'escuro'], answer: 2 },
    ],
  },

  // ═══ 16 · Körper & Gesundheit ═══
  {
    id: 'a12-koerper',
    level: 'a12',
    num: '16',
    title: 'Körper & Gesundheit',
    subtitle: 'O corpo, sintomas e ir ao médico',
    shape: 'triangle',
    minutes: 30,
    vocabTags: ['koerper', 'frases'],
    sections: [
      { kind: 'text', title: 'A ideia', body: 'Saber dizer o que dói é essencial para viver no exterior. Aqui vêm as partes do corpo, os sintomas, o verbo wehtun (doer, + Dativo) e o diálogo completo de uma consulta.' },
      {
        kind: 'table',
        title: 'O corpo (der Körper)',
        head: ['Alemão', 'Português', 'Plural'],
        rows: [
          ['der Kopf', 'cabeça', 'die Köpfe'],
          ['das Auge', 'olho', 'die Augen'],
          ['das Ohr', 'orelha', 'die Ohren'],
          ['die Nase', 'nariz', 'die Nasen'],
          ['der Mund', 'boca', 'die Münder'],
          ['der Hals', 'pescoço/garganta', 'die Hälse'],
          ['der Arm', 'braço', 'die Arme'],
          ['die Hand', 'mão', 'die Hände'],
          ['der Bauch', 'barriga', 'die Bäuche'],
          ['das Bein', 'perna', 'die Beine'],
          ['der Fuß', 'pé', 'die Füße'],
          ['der Rücken', 'costas', 'die Rücken'],
        ],
      },
      {
        kind: 'table',
        title: 'Sintomas (die Symptome)',
        head: ['Alemão', 'Português'],
        rows: [
          ['Ich habe Kopfschmerzen.', 'Estou com dor de cabeça.'],
          ['Ich habe Bauchschmerzen.', 'Estou com dor de barriga.'],
          ['Ich habe Halsschmerzen.', 'Estou com dor de garganta.'],
          ['Ich habe Fieber.', 'Estou com febre.'],
          ['Ich habe Husten.', 'Estou com tosse.'],
          ['Ich habe Schnupfen.', 'Estou com coriza/resfriado.'],
          ['Mir ist schlecht.', 'Estou enjoado/passando mal.'],
          ['Ich bin erkältet.', 'Estou resfriado.'],
        ],
        note: 'Dor = -schmerzen (plural). Parte do corpo + schmerzen: Kopf+schmerzen, Zahn+schmerzen.',
      },
      { kind: 'tip', title: 'wehtun + Dativo', body: 'Alternativa a "Schmerzen haben": "Mein Kopf tut mir weh" (minha cabeça me dói). Plural → tun: "Meine Beine tun mir weh." A pessoa que sente vai no Dativo (mir/dir/ihm).' },
      {
        kind: 'table',
        title: 'Na consulta (beim Arzt)',
        head: ['Quem', 'Frase', 'Tradução'],
        rows: [
          ['médico', 'Was fehlt Ihnen?', 'O que o senhor tem?'],
          ['paciente', 'Ich habe seit gestern Fieber.', 'Estou com febre desde ontem.'],
          ['médico', 'Ich untersuche Sie mal.', 'Vou examiná-lo.'],
          ['médico', 'Sie haben eine Erkältung.', 'O senhor está resfriado.'],
          ['médico', 'Nehmen Sie diese Tabletten.', 'Tome estes comprimidos.'],
          ['médico', 'Sie sollen im Bett bleiben.', 'O senhor deve ficar de cama.'],
          ['despedida', 'Gute Besserung!', 'Melhoras!'],
        ],
      },
      { kind: 'tip', title: 'Conselhos com sollen', body: 'O médico manda conselhos com sollen: "Sie sollen viel Wasser trinken / viel schlafen / nicht rauchen." É o modal do conselho de terceiro que você viu em Modalverben.' },
      {
        kind: 'examples',
        title: 'Frases-modelo',
        items: [
          { de: 'Ich habe seit zwei Tagen Kopfschmerzen.', pt: 'Estou com dor de cabeça há dois dias.' },
          { de: 'Mein Hals tut mir weh.', pt: 'Minha garganta dói.' },
          { de: 'Ich brauche einen Termin beim Arzt.', pt: 'Preciso de uma consulta no médico.' },
          { de: 'Nehmen Sie die Tabletten dreimal am Tag.', pt: 'Tome os comprimidos três vezes ao dia.' },
          { de: 'Sie sollen zu Hause bleiben.', pt: 'O senhor deve ficar em casa.' },
          { de: 'Gute Besserung!', pt: 'Melhoras!' },
        ],
      },
      {
        kind: 'dialog',
        title: 'Dialog — Beim Arzt',
        lines: [
          { who: 'Ärztin', de: 'Guten Tag! Was fehlt Ihnen?', pt: 'Bom dia! O que o senhor tem?' },
          { who: 'Paulo', de: 'Ich habe Kopfschmerzen und Fieber, seit gestern.', pt: 'Estou com dor de cabeça e febre, desde ontem.' },
          { who: 'Ärztin', de: 'Haben Sie auch Husten?', pt: 'Tem tosse também?' },
          { who: 'Paulo', de: 'Ja, ein bisschen. Und mein Hals tut mir weh.', pt: 'Sim, um pouco. E minha garganta dói.' },
          { who: 'Ärztin', de: 'Sie haben eine Erkältung. Nichts Schlimmes.', pt: 'O senhor está resfriado. Nada grave.' },
          { who: 'Paulo', de: 'Was soll ich machen?', pt: 'O que eu devo fazer?' },
          { who: 'Ärztin', de: 'Nehmen Sie diese Tabletten und bleiben Sie im Bett. Gute Besserung!', pt: 'Tome estes comprimidos e fique de cama. Melhoras!' },
        ],
      },
      {
        kind: 'fehler',
        title: 'Erros clássicos de brasileiros',
        pairs: [
          { falsch: 'Ich bin Kopfschmerzen.', richtig: 'Ich habe Kopfschmerzen.', why: 'Sintoma: haben, não sein.' },
          { falsch: 'Mein Kopf tut mich weh.', richtig: 'Mein Kopf tut mir weh.', why: 'wehtun pede Dativo (mir).' },
          { falsch: 'Meine Beine tut weh.', richtig: 'Meine Beine tun weh.', why: 'Sujeito plural (Beine) → tun.' },
          { falsch: 'Ich bin krank seit gestern → Ich bin seit gestern krank. (ordem)', richtig: 'Ich bin seit gestern krank.', why: 'Tempo (seit gestern) vem antes do adjetivo.' },
        ],
      },
      { kind: 'tip', title: 'Método', body: 'Aponte para 5 partes do corpo e diga "Mein/Meine ___ tut/tun mir weh". Depois simule a consulta inteira (paciente + médico). Você raramente treina isso — até precisar de verdade.' },
    ],
    quiz: [
      { kind: 'gap', before: 'Ich ', after: ' Kopfschmerzen. (ter)', answer: ['habe'] },
      { kind: 'gap', before: 'Mein Kopf tut ', after: ' weh. (a mim)', answer: ['mir'] },
      { kind: 'choice', prompt: '"der Bauch" é…', options: ['a cabeça', 'a barriga', 'as costas', 'a garganta'], answer: 1 },
      { kind: 'gap', before: 'Meine Beine ', after: ' mir weh. (doer, plural)', answer: ['tun'] },
      { kind: 'choice', prompt: 'Médico pergunta:', options: ['Wie heißt du?', 'Was fehlt Ihnen?', 'Woher kommen Sie?', 'Was kostet das?'], answer: 1 },
      { kind: 'choice', prompt: '"Gute Besserung!" significa…', options: ['Bom apetite!', 'Boa sorte!', 'Melhoras!', 'Até logo!'], answer: 2 },
      { kind: 'gap', before: 'Sie ', after: ' im Bett bleiben. (conselho — sollen)', answer: ['sollen'] },
      { kind: 'choice', prompt: '"die Hand" no plural:', options: ['die Hands', 'die Hände', 'die Handen', 'die Händer'], answer: 1 },
      { kind: 'order', words: ['Ich', 'habe', 'seit', 'gestern', 'Fieber'], answer: 'Ich habe seit gestern Fieber' },
      { kind: 'choice', prompt: '"Ich bin erkältet" =', options: ['Estou com fome', 'Estou resfriado', 'Estou cansado', 'Estou com calor'], answer: 1 },
    ],
  },

  // ═══ 17 · Wetter & Jahreszeiten ═══
  {
    id: 'a12-wetter',
    level: 'a12',
    num: '17',
    title: 'Wetter & Jahreszeiten',
    subtitle: 'O tempo, as estações, a temperatura',
    shape: 'circle',
    minutes: 25,
    vocabTags: ['wetter', 'tempo'],
    sections: [
      { kind: 'text', title: 'A ideia', body: 'Falar do tempo é o small talk universal — e no alemão usa muito o "es" impessoal: es regnet, es schneit. Aqui vêm estações, clima, temperatura e a comparação Brasil × Alemanha (estações invertidas!).' },
      {
        kind: 'table',
        title: 'As estações (die Jahreszeiten)',
        head: ['Alemão', 'Português', 'Meses'],
        rows: [
          ['der Frühling', 'primavera', 'März–Mai'],
          ['der Sommer', 'verão', 'Juni–August'],
          ['der Herbst', 'outono', 'September–November'],
          ['der Winter', 'inverno', 'Dezember–Februar'],
        ],
        note: 'im + estação: im Sommer, im Winter. Todas são masculinas (der).',
      },
      {
        kind: 'table',
        title: 'Como está o tempo? (Wie ist das Wetter?)',
        head: ['Alemão', 'Português'],
        rows: [
          ['Es ist sonnig.', 'Está ensolarado.'],
          ['Es ist bewölkt.', 'Está nublado.'],
          ['Es ist windig.', 'Está ventando.'],
          ['Es ist neblig.', 'Está com neblina.'],
          ['Es regnet.', 'Está chovendo.'],
          ['Es schneit.', 'Está nevando.'],
          ['Es ist warm / heiß.', 'Está quente / muito quente.'],
          ['Es ist kalt / kühl.', 'Está frio / fresco.'],
        ],
      },
      {
        kind: 'table',
        title: 'A temperatura',
        head: ['Alemão', 'Português'],
        rows: [
          ['Es sind 25 Grad.', 'Estão 25 graus.'],
          ['Es sind minus 5 Grad.', 'Estão 5 graus negativos.'],
          ['Wie warm ist es?', 'Quantos graus faz?'],
          ['die Temperatur', 'a temperatura'],
        ],
      },
      { kind: 'tip', title: 'O "es" impessoal', body: 'Fenômenos do tempo usam "es" como sujeito vazio: Es regnet (chove), Es schneit (neva), Es ist kalt. Não há "eu/você" — é o clima agindo sozinho. Mesma lógica de "está chovendo" em PT.' },
      {
        kind: 'examples',
        title: 'Frases-modelo',
        items: [
          { de: 'Wie ist das Wetter heute?', pt: 'Como está o tempo hoje?' },
          { de: 'Im Sommer ist es warm und sonnig.', pt: 'No verão está quente e ensolarado.' },
          { de: 'Im Winter schneit es oft.', pt: 'No inverno neva com frequência.' },
          { de: 'Heute regnet es und es ist windig.', pt: 'Hoje chove e está ventando.' },
          { de: 'Es sind nur 5 Grad. Zieh eine Jacke an!', pt: 'Estão só 5 graus. Vista uma jaqueta!' },
          { de: 'Bei Regen bleibe ich zu Hause.', pt: 'Quando chove, fico em casa.' },
        ],
      },
      {
        kind: 'dialog',
        title: 'Dialog — Sommer und Winter',
        lines: [
          { who: 'Lena', de: 'Wie ist das Wetter gerade in Brasilien?', pt: 'Como está o tempo agora no Brasil?' },
          { who: 'Paulo', de: 'Es ist Winter, aber es sind noch 22 Grad!', pt: 'É inverno, mas ainda faz 22 graus!' },
          { who: 'Lena', de: 'Winter mit 22 Grad? Hier schneit es gerade!', pt: 'Inverno com 22 graus? Aqui está nevando!' },
          { who: 'Paulo', de: 'In Brasilien sind die Jahreszeiten umgekehrt.', pt: 'No Brasil as estações são invertidas.' },
          { who: 'Lena', de: 'Und wann ist Sommer bei euch?', pt: 'E quando é verão aí?' },
          { who: 'Paulo', de: 'Im Dezember und Januar. Dann ist es sehr heiß.', pt: 'Em dezembro e janeiro. Aí faz muito calor.' },
        ],
      },
      {
        kind: 'fehler',
        title: 'Erros clássicos de brasileiros',
        pairs: [
          { falsch: 'Das Wetter regnet.', richtig: 'Es regnet.', why: 'Fenômeno do tempo usa "es" impessoal.' },
          { falsch: 'Es ist 25 Grad.', richtig: 'Es sind 25 Grad.', why: 'Graus é plural → sind.' },
          { falsch: 'in Sommer', richtig: 'im Sommer', why: 'im (in dem) + estação.' },
          { falsch: 'Es macht kalt.', richtig: 'Es ist kalt.', why: 'Clima com sein, não machen (germanismo do francês/PT).' },
        ],
      },
      { kind: 'tip', title: 'Método', body: 'Todo dia, ao acordar, descreva o tempo em 2 frases ("Heute ist es… und es sind … Grad"). É o hábito de small talk que mais aparece e o mais fácil de automatizar.' },
    ],
    quiz: [
      { kind: 'gap', before: '', after: ' regnet. (está chovendo)', answer: ['Es'] },
      { kind: 'gap', before: 'Es ', after: ' 25 Grad. (estão)', answer: ['sind'] },
      { kind: 'choice', prompt: '"der Winter" é…', options: ['primavera', 'verão', 'outono', 'inverno'], answer: 3 },
      { kind: 'gap', before: '', after: ' Sommer ist es warm. (no verão)', answer: ['Im'] },
      { kind: 'choice', prompt: '"Es schneit" =', options: ['Está ventando', 'Está nevando', 'Está chovendo', 'Está ensolarado'], answer: 1 },
      { kind: 'choice', prompt: 'No Brasil, quando é verão?', options: ['Juni–August', 'Dezember–Januar', 'März–Mai', 'September'], answer: 1 },
      { kind: 'gap', before: 'Heute ist es ', after: '. (nublado)', answer: ['bewölkt'] },
      { kind: 'choice', prompt: 'Frase correta:', options: ['Es macht kalt.', 'Das Wetter ist regnen.', 'Es ist kalt.', 'Es hat kalt.'], answer: 2 },
      { kind: 'order', words: ['Im', 'Winter', 'schneit', 'es', 'oft'], answer: 'Im Winter schneit es oft' },
      { kind: 'choice', prompt: '"umgekehrt" significa…', options: ['quente', 'invertido', 'nublado', 'frio'], answer: 1 },
    ],
  },

  // ═══ 18 · Datum, Ordinalzahlen & Termine ═══
  {
    id: 'a12-datum',
    level: 'a12',
    num: '18',
    title: 'Datum & Termine',
    subtitle: 'Data, números ordinais e marcar compromissos',
    shape: 'square',
    minutes: 30,
    vocabTags: ['zahlen-zeit', 'frases'],
    sections: [
      { kind: 'text', title: 'A ideia', body: 'Dizer a data, o aniversário e marcar consulta exige os números ORDINAIS (primeiro, segundo…) — que têm uma regra simples e três exceções. Depois é só encaixar no "am".' },
      {
        kind: 'table',
        title: 'Números ordinais — a regra',
        head: ['Faixa', 'Regra', 'Exemplo'],
        rows: [
          ['1–19', 'número + -te', 'vier→vierte, zehn→zehnte'],
          ['20+', 'número + -ste', 'zwanzig→zwanzigste, hundert→hundertste'],
        ],
        note: 'Exceções irregulares: erste (1º), dritte (3º), siebte (7º), achte (8º).',
      },
      {
        kind: 'table',
        title: 'Os ordinais que caem em prova',
        head: ['Número', 'Ordinal', 'Português'],
        rows: [
          ['1.', 'erste', 'primeiro'],
          ['2.', 'zweite', 'segundo'],
          ['3.', 'dritte', 'terceiro'],
          ['4.', 'vierte', 'quarto'],
          ['7.', 'siebte', 'sétimo'],
          ['8.', 'achte', 'oitavo'],
          ['11.', 'elfte', 'décimo primeiro'],
          ['20.', 'zwanzigste', 'vigésimo'],
          ['31.', 'einunddreißigste', 'trigésimo primeiro'],
        ],
      },
      {
        kind: 'table',
        title: 'Perguntar e dizer a data',
        head: ['Alemão', 'Português'],
        rows: [
          ['Der Wievielte ist heute?', 'Que dia é hoje?'],
          ['Heute ist der elfte Juli.', 'Hoje é onze de julho.'],
          ['Wann hast du Geburtstag?', 'Quando é seu aniversário?'],
          ['Am elften Juli. / Im Juli.', 'Em onze de julho. / Em julho.'],
          ['Welches Datum haben wir?', 'Em que data estamos?'],
        ],
        note: 'am + ordinal + -n: am elftEN Juli (o ordinal ganha -n depois de "am").',
      },
      {
        kind: 'table',
        title: 'Marcar compromissos (der Termin)',
        head: ['Função', 'Frase', 'Tradução'],
        rows: [
          ['marcar', 'Ich möchte einen Termin.', 'Quero marcar um horário.'],
          ['propor', 'Passt es Ihnen am Montag?', 'Segunda serve para o senhor?'],
          ['aceitar', 'Ja, das passt mir.', 'Sim, isso me serve.'],
          ['recusar', 'Nein, da kann ich nicht.', 'Não, nesse dia não posso.'],
          ['cancelar', 'Ich muss den Termin absagen.', 'Preciso cancelar o horário.'],
        ],
      },
      { kind: 'tip', title: 'Feriados alemães', body: 'Weihnachten (Natal, 25.12), Silvester (véspera de Ano Novo, 31.12), Neujahr (Ano Novo, 1.1), Ostern (Páscoa). "Frohe Weihnachten!" = Feliz Natal. "Guten Rutsch!" = Bom Ano Novo (informal).' },
      {
        kind: 'examples',
        title: 'Frases-modelo',
        items: [
          { de: 'Heute ist der zwölfte Juli.', pt: 'Hoje é doze de julho.' },
          { de: 'Ich habe am dritten März Geburtstag.', pt: 'Meu aniversário é em três de março.' },
          { de: 'Passt Ihnen der Termin am Dienstag um 15 Uhr?', pt: 'Serve o horário na terça às 15h?' },
          { de: 'Nein, da kann ich leider nicht.', pt: 'Não, nesse dia infelizmente não posso.' },
          { de: 'Frohe Weihnachten und einen guten Rutsch!', pt: 'Feliz Natal e um bom Ano Novo!' },
          { de: 'Mein Termin ist am einunddreißigsten.', pt: 'Meu horário é no dia trinta e um.' },
        ],
      },
      {
        kind: 'dialog',
        title: 'Dialog — Einen Termin machen',
        lines: [
          { who: 'Praxis', de: 'Praxis Dr. Müller, guten Tag!', pt: 'Consultório Dr. Müller, bom dia!' },
          { who: 'Paulo', de: 'Guten Tag, ich möchte einen Termin.', pt: 'Bom dia, quero marcar um horário.' },
          { who: 'Praxis', de: 'Passt es Ihnen am Montag, dem fünften, um zehn Uhr?', pt: 'Serve segunda, dia cinco, às dez?' },
          { who: 'Paulo', de: 'Nein, am Montag kann ich nicht. Und Dienstag?', pt: 'Não, segunda não posso. E terça?' },
          { who: 'Praxis', de: 'Dienstag, der sechste, um vierzehn Uhr?', pt: 'Terça, dia seis, às catorze?' },
          { who: 'Paulo', de: 'Ja, das passt mir gut. Danke!', pt: 'Sim, isso me serve. Obrigado!' },
        ],
      },
      {
        kind: 'fehler',
        title: 'Erros clássicos de brasileiros',
        pairs: [
          { falsch: 'Heute ist der siebte → der siebente? ', richtig: 'der siebte', why: '7º é irregular: siebte (não "siebente").' },
          { falsch: 'am elfte Juli', richtig: 'am elften Juli', why: 'Depois de "am" o ordinal ganha -n.' },
          { falsch: 'Ich habe Geburtstag in 3. März.', richtig: 'Ich habe am dritten März Geburtstag.', why: 'Data com dia → am + ordinal.' },
          { falsch: 'der dreite', richtig: 'der dritte', why: '3º é irregular: dritte.' },
        ],
      },
      { kind: 'tip', title: 'Método', body: 'Diga em voz alta as datas importantes da sua vida (aniversários da família, feriados) em alemão. Ordinais só grudam quando ligados a datas reais que você repete.' },
    ],
    quiz: [
      { kind: 'choice', prompt: 'O ordinal de "7":', options: ['siebente', 'siebte', 'siebende', 'siebse'], answer: 1 },
      { kind: 'choice', prompt: 'O ordinal de "3":', options: ['dreite', 'dritte', 'drießte', 'dreiste'], answer: 1 },
      { kind: 'gap', before: 'Heute ist der ', after: ' Juli. (12º)', answer: ['zwölfte'] },
      { kind: 'gap', before: 'Ich habe am ', after: ' März Geburtstag. (3º + n)', answer: ['dritten'] },
      { kind: 'choice', prompt: 'Ordinal de "20":', options: ['zwanzigte', 'zwanzigste', 'zwanziger', 'zwanzigende'], answer: 1, hint: '20+ usa -ste' },
      { kind: 'choice', prompt: '"Der Wievielte ist heute?" pergunta…', options: ['a hora', 'a data', 'o dia da semana', 'o tempo'], answer: 1 },
      { kind: 'gap', before: 'Passt es Ihnen am ', after: '? (na terça)', answer: ['Dienstag'] },
      { kind: 'choice', prompt: '"Guten Rutsch!" deseja…', options: ['Bom apetite', 'Boas melhoras', 'Bom Ano Novo', 'Boa viagem'], answer: 2 },
      { kind: 'order', words: ['Ich', 'möchte', 'einen', 'Termin'], answer: 'Ich möchte einen Termin' },
      { kind: 'gap', before: 'Mein Termin ist am ', after: ' Juli. (11º + n)', answer: ['elften'] },
    ],
  },

  // ═══ 19 · Vorstellung komplett ═══
  {
    id: 'a12-vorstellung',
    level: 'a12',
    num: '19',
    title: 'Vorstellung komplett',
    subtitle: 'Apresentar-se de ponta a ponta — o Sprechen do exame',
    shape: 'cross',
    minutes: 25,
    vocabTags: ['apresentacao', 'frases'],
    sections: [
      { kind: 'text', title: 'O roteiro da aula 13', body: 'A prova oral (Goethe A1, Sprechen Teil 1) e a vida começam com você falando de si por ~2 minutos. A aula definiu 10 blocos — decore uma frase por bloco e a apresentação sai sozinha.' },
      {
        kind: 'table',
        title: 'Os 10 blocos + frase-modelo',
        head: ['#', 'Bloco', 'Frase-modelo'],
        rows: [
          ['1', 'Name', 'Ich heiße Lucas. / Mein Name ist Lucas.'],
          ['2', 'Alter', 'Ich bin 25 Jahre alt.'],
          ['3', 'Land', 'Ich komme aus Brasilien.'],
          ['4', 'Wohnort', 'Ich wohne in São Paulo.'],
          ['5', 'Unterricht', 'Ich lerne Deutsch seit sechs Monaten.'],
          ['6', 'Sprache', 'Ich spreche Portugiesisch, Englisch und ein bisschen Deutsch.'],
          ['7', 'Hobbys', 'Meine Hobbys sind Sport und Programmieren.'],
          ['8', 'Haustier', 'Ich habe einen Hund. / Ich habe kein Haustier.'],
          ['9', 'Beruf', 'Ich bin Student. / Ich arbeite als Entwickler.'],
          ['10', 'Telefonnummer', 'Meine Telefonnummer ist null-eins-eins…'],
        ],
      },
      {
        kind: 'table',
        title: 'Variações para não soar decorado',
        head: ['Bloco', 'Variação 1', 'Variação 2'],
        rows: [
          ['Name', 'Ich heiße…', 'Mein Name ist…'],
          ['Land', 'Ich komme aus…', 'Ich bin aus…'],
          ['Beruf', 'Ich bin…', 'Ich arbeite als…'],
          ['Hobbys', 'Meine Hobbys sind…', 'In meiner Freizeit … ich gern…'],
        ],
      },
      { kind: 'tip', title: 'Sprechen Teil 1 — o que o examinador faz', body: 'Ele pede que você fale de si e depois faz perguntas curtas ("Wie ist Ihr Name?", "Buchstabieren Sie bitte!", "Wie ist Ihre Telefonnummer?"). Treine BUCHSTABIEREN (soletrar) e ditar o telefone dígito a dígito — cai sempre.' },
      {
        kind: 'examples',
        title: 'A apresentação inteira (shadowing!)',
        items: [
          { de: 'Hallo! Ich heiße Lucas und ich bin 25 Jahre alt.', pt: 'Olá! Me chamo Lucas e tenho 25 anos.' },
          { de: 'Ich komme aus Brasilien und wohne in São Paulo.', pt: 'Venho do Brasil e moro em São Paulo.' },
          { de: 'Ich lerne Deutsch seit sechs Monaten.', pt: 'Estudo alemão há seis meses.' },
          { de: 'Meine Hobbys sind Sport, Musik und Programmieren.', pt: 'Meus hobbies são esporte, música e programação.' },
          { de: 'Ich arbeite als Entwickler.', pt: 'Trabalho como desenvolvedor.' },
          { de: 'Meine Telefonnummer ist null-eins-fünf…', pt: 'Meu telefone é zero-um-cinco…' },
        ],
      },
      {
        kind: 'dialog',
        title: 'Dialog — Die mündliche Prüfung',
        lines: [
          { who: 'Prüfer', de: 'Guten Tag. Bitte stellen Sie sich vor.', pt: 'Bom dia. Por favor, apresente-se.' },
          { who: 'Paulo', de: 'Ich heiße Paulo, ich bin 28 und komme aus Brasilien.', pt: 'Me chamo Paulo, tenho 28 e venho do Brasil.' },
          { who: 'Prüfer', de: 'Buchstabieren Sie bitte Ihren Nachnamen.', pt: 'Soletre seu sobrenome, por favor.' },
          { who: 'Paulo', de: 'S-I-L-V-A. Silva.', pt: 'S-I-L-V-A. Silva.' },
          { who: 'Prüfer', de: 'Und wie ist Ihre Telefonnummer?', pt: 'E qual é o seu telefone?' },
          { who: 'Paulo', de: 'Null-eins-fünf-drei-zwei…', pt: 'Zero-um-cinco-três-dois…' },
          { who: 'Prüfer', de: 'Danke. Was sind Ihre Hobbys?', pt: 'Obrigado. Quais são seus hobbies?' },
          { who: 'Paulo', de: 'Ich spiele gern Fußball und höre Musik.', pt: 'Gosto de jogar futebol e ouvir música.' },
        ],
      },
      {
        kind: 'fehler',
        title: 'Erros clássicos de brasileiros',
        pairs: [
          { falsch: 'Ich habe 25 Jahre.', richtig: 'Ich bin 25 Jahre alt.', why: 'Idade com sein, não haben (germanismo do PT).' },
          { falsch: 'Ich lerne Deutsch seit sechs Monate.', richtig: 'Ich lerne Deutsch seit sechs Monaten.', why: 'seit + Dativo plural: Monaten.' },
          { falsch: 'Mein Name ist Silva. (só sobrenome)', richtig: 'Ich heiße Paulo Silva.', why: 'Dê nome + sobrenome quando pedirem para se apresentar.' },
          { falsch: 'Ich bin Entwickler von Beruf ist…', richtig: 'Ich bin Entwickler.', why: 'Não misture as fórmulas; escolha uma.' },
        ],
      },
      { kind: 'tip', title: 'Método', body: 'Grave-se falando os 10 blocos SEM ler. Onde travar = bloco fraco → revisa o módulo correspondente. Repita 1× por semana; o tempo até 2 minutos fluidos é seu termômetro de A1.' },
    ],
    quiz: [
      { kind: 'gap', before: 'Ich ', after: ' aus Brasilien.', answer: ['komme'] },
      { kind: 'gap', before: 'Ich ', after: ' in São Paulo.', answer: ['wohne'] },
      { kind: 'gap', before: 'Ich lerne Deutsch ', after: ' sechs Monaten.', answer: ['seit'], hint: 'há quanto tempo → Dativo' },
      { kind: 'choice', prompt: '"Trabalho como desenvolvedor" =', options: ['Ich arbeite als Entwickler.', 'Ich arbeite wie Entwickler.', 'Ich bin arbeiten Entwickler.', 'Ich arbeite für Entwickler.'], answer: 0 },
      { kind: 'choice', prompt: '"Tenho 25 anos" =', options: ['Ich habe 25 Jahre.', 'Ich bin 25 Jahre alt.', 'Ich habe 25 Jahre alt.', 'Ich bin 25 Jahre.'], answer: 1 },
      { kind: 'order', words: ['Meine', 'Hobbys', 'sind', 'Sport', 'und', 'Musik'], answer: 'Meine Hobbys sind Sport und Musik' },
      { kind: 'choice', prompt: '"Buchstabieren Sie!" pede para você…', options: ['falar mais alto', 'soletrar', 'repetir', 'traduzir'], answer: 1 },
      { kind: 'gap', before: 'Ich ', after: ' Lucas. (me chamo)', answer: ['heiße'] },
      { kind: 'gap', before: 'Ich lerne Deutsch seit sechs ', after: '. (meses — Dativo)', answer: ['Monaten'] },
      { kind: 'choice', prompt: 'Na prova, ao pedirem seu nome, você dá…', options: ['só o primeiro nome', 'nome e sobrenome', 'só o sobrenome', 'o apelido'], answer: 1 },
    ],
  },
]
