import type { Verb } from './types'

// Tabelas de conjugação — Präsens [ich, du, er/sie/es, wir, ihr, sie/Sie]
// + Partizip II e auxiliar para o Perfekt.

export const VERBS: Verb[] = [
  // ── Modais (aula DEUTSCHUNTERRICHT 11) ────────────────────────────
  { inf: 'können', pt: 'poder, conseguir', type: 'modal', praesens: ['kann', 'kannst', 'kann', 'können', 'könnt', 'können'], note: 'Habilidade: "Thomas kann sehr gut tanzen."' },
  { inf: 'dürfen', pt: 'ter permissão', type: 'modal', praesens: ['darf', 'darfst', 'darf', 'dürfen', 'dürft', 'dürfen'], note: 'Permissão/proibição: "Man darf nicht in der Klasse essen."' },
  { inf: 'möchten', pt: 'gostaria de', type: 'modal', praesens: ['möchte', 'möchtest', 'möchte', 'möchten', 'möchtet', 'möchten'], note: 'Desejo educado: "Ich möchte ein Brot, bitte."' },
  { inf: 'wollen', pt: 'querer', type: 'modal', praesens: ['will', 'willst', 'will', 'wollen', 'wollt', 'wollen'], note: 'Vontade forte: "Daniel will nach Deutschland reisen."' },
  { inf: 'müssen', pt: 'ter que, precisar', type: 'modal', praesens: ['muss', 'musst', 'muss', 'müssen', 'müsst', 'müssen'], note: 'Obrigação: "Ich muss heute lernen."' },
  { inf: 'sollen', pt: 'dever (conselho)', type: 'modal', praesens: ['soll', 'sollst', 'soll', 'sollen', 'sollt', 'sollen'], note: 'Conselho/ordem de terceiro: "Sie soll zu Hause bleiben."' },

  // ── Irregulares essenciais ────────────────────────────────────────
  { inf: 'sein', pt: 'ser, estar', type: 'irregular', praesens: ['bin', 'bist', 'ist', 'sind', 'seid', 'sind'], partizip: 'gewesen', aux: 'sein' },
  { inf: 'haben', pt: 'ter', type: 'irregular', praesens: ['habe', 'hast', 'hat', 'haben', 'habt', 'haben'], partizip: 'gehabt', aux: 'haben' },
  { inf: 'werden', pt: 'tornar-se, ficar', type: 'irregular', praesens: ['werde', 'wirst', 'wird', 'werden', 'werdet', 'werden'], partizip: 'geworden', aux: 'sein' },
  { inf: 'fahren', pt: 'ir (de veículo)', type: 'irregular', praesens: ['fahre', 'fährst', 'fährt', 'fahren', 'fahrt', 'fahren'], partizip: 'gefahren', aux: 'sein', note: 'a→ä no du/er' },
  { inf: 'sprechen', pt: 'falar', type: 'irregular', praesens: ['spreche', 'sprichst', 'spricht', 'sprechen', 'sprecht', 'sprechen'], partizip: 'gesprochen', aux: 'haben', note: 'e→i no du/er' },
  { inf: 'essen', pt: 'comer', type: 'irregular', praesens: ['esse', 'isst', 'isst', 'essen', 'esst', 'essen'], partizip: 'gegessen', aux: 'haben', note: 'e→i no du/er' },
  { inf: 'lesen', pt: 'ler', type: 'irregular', praesens: ['lese', 'liest', 'liest', 'lesen', 'lest', 'lesen'], partizip: 'gelesen', aux: 'haben', note: 'e→ie no du/er' },
  { inf: 'sehen', pt: 'ver', type: 'irregular', praesens: ['sehe', 'siehst', 'sieht', 'sehen', 'seht', 'sehen'], partizip: 'gesehen', aux: 'haben', note: 'e→ie no du/er' },
  { inf: 'nehmen', pt: 'pegar, tomar', type: 'irregular', praesens: ['nehme', 'nimmst', 'nimmt', 'nehmen', 'nehmt', 'nehmen'], partizip: 'genommen', aux: 'haben', note: 'e→imm no du/er' },
  { inf: 'geben', pt: 'dar', type: 'irregular', praesens: ['gebe', 'gibst', 'gibt', 'geben', 'gebt', 'geben'], partizip: 'gegeben', aux: 'haben', note: 'e→i no du/er' },
  { inf: 'schlafen', pt: 'dormir', type: 'irregular', praesens: ['schlafe', 'schläfst', 'schläft', 'schlafen', 'schlaft', 'schlafen'], partizip: 'geschlafen', aux: 'haben', note: 'a→ä no du/er' },
  { inf: 'gehen', pt: 'ir (a pé)', type: 'irregular', praesens: ['gehe', 'gehst', 'geht', 'gehen', 'geht', 'gehen'], partizip: 'gegangen', aux: 'sein' },
  { inf: 'kommen', pt: 'vir', type: 'irregular', praesens: ['komme', 'kommst', 'kommt', 'kommen', 'kommt', 'kommen'], partizip: 'gekommen', aux: 'sein' },
  { inf: 'fliegen', pt: 'voar', type: 'irregular', praesens: ['fliege', 'fliegst', 'fliegt', 'fliegen', 'fliegt', 'fliegen'], partizip: 'geflogen', aux: 'sein' },
  { inf: 'bleiben', pt: 'ficar', type: 'irregular', praesens: ['bleibe', 'bleibst', 'bleibt', 'bleiben', 'bleibt', 'bleiben'], partizip: 'geblieben', aux: 'sein' },
  { inf: 'trinken', pt: 'beber', type: 'irregular', praesens: ['trinke', 'trinkst', 'trinkt', 'trinken', 'trinkt', 'trinken'], partizip: 'getrunken', aux: 'haben' },
  { inf: 'helfen', pt: 'ajudar (+Dativ)', type: 'irregular', praesens: ['helfe', 'hilfst', 'hilft', 'helfen', 'helft', 'helfen'], partizip: 'geholfen', aux: 'haben', note: 'e→i no du/er' },
  { inf: 'wissen', pt: 'saber (fato)', type: 'irregular', praesens: ['weiß', 'weißt', 'weiß', 'wissen', 'wisst', 'wissen'], partizip: 'gewusst', aux: 'haben', note: 'Conjuga como modal: ich weiß / er weiß (sem -t). "Ich weiß es nicht."' },
  { inf: 'mögen', pt: 'gostar de', type: 'irregular', praesens: ['mag', 'magst', 'mag', 'mögen', 'mögt', 'mögen'], partizip: 'gemocht', aux: 'haben', note: 'Conjuga como modal. Como verbo principal: "Ich mag Pizza."' },
  { inf: 'finden', pt: 'achar, encontrar', type: 'irregular', praesens: ['finde', 'findest', 'findet', 'finden', 'findet', 'finden'], partizip: 'gefunden', aux: 'haben', note: '-d- pede "e" extra: du findest. "Wie findest du den Film?"' },
  { inf: 'treffen', pt: 'encontrar (pessoas)', type: 'irregular', praesens: ['treffe', 'triffst', 'trifft', 'treffen', 'trefft', 'treffen'], partizip: 'getroffen', aux: 'haben', note: 'e→i no du/er: "Ich treffe Freunde im Café."' },
  { inf: 'tragen', pt: 'vestir, usar; carregar', type: 'irregular', praesens: ['trage', 'trägst', 'trägt', 'tragen', 'tragt', 'tragen'], partizip: 'getragen', aux: 'haben', note: 'a→ä no du/er: "Sie trägt ein Kleid."' },
  { inf: 'waschen', pt: 'lavar', type: 'irregular', praesens: ['wasche', 'wäschst', 'wäscht', 'waschen', 'wascht', 'waschen'], partizip: 'gewaschen', aux: 'haben', note: 'a→ä no du/er: "Ich wasche mir die Hände."' },
  { inf: 'laufen', pt: 'correr, andar', type: 'irregular', praesens: ['laufe', 'läufst', 'läuft', 'laufen', 'lauft', 'laufen'], partizip: 'gelaufen', aux: 'sein', note: 'au→äu no du/er' },
  { inf: 'schwimmen', pt: 'nadar', type: 'irregular', praesens: ['schwimme', 'schwimmst', 'schwimmt', 'schwimmen', 'schwimmt', 'schwimmen'], partizip: 'geschwommen', aux: 'sein', note: '"Ich bin im Meer geschwommen."' },
  { inf: 'schreiben', pt: 'escrever', type: 'irregular', praesens: ['schreibe', 'schreibst', 'schreibt', 'schreiben', 'schreibt', 'schreiben'], partizip: 'geschrieben', aux: 'haben' },
  { inf: 'singen', pt: 'cantar', type: 'irregular', praesens: ['singe', 'singst', 'singt', 'singen', 'singt', 'singen'], partizip: 'gesungen', aux: 'haben' },
  { inf: 'verstehen', pt: 'entender', type: 'irregular', praesens: ['verstehe', 'verstehst', 'versteht', 'verstehen', 'versteht', 'verstehen'], partizip: 'verstanden', aux: 'haben', note: 'INSEPARÁVEL (ver-) → Partizip SEM ge-: verstanden. "Ich habe das nicht verstanden."' },
  { inf: 'bekommen', pt: 'receber, ganhar', type: 'irregular', praesens: ['bekomme', 'bekommst', 'bekommt', 'bekommen', 'bekommt', 'bekommen'], partizip: 'bekommen', aux: 'haben', note: 'INSEPARÁVEL (be-) → Partizip SEM ge-: bekommen (igual ao infinitivo!). Não é "become".' },
  { inf: 'vergessen', pt: 'esquecer', type: 'irregular', praesens: ['vergesse', 'vergisst', 'vergisst', 'vergessen', 'vergesst', 'vergessen'], partizip: 'vergessen', aux: 'haben', note: 'e→i no du/er; INSEPARÁVEL (ver-) → Partizip SEM ge-: vergessen.' },

  // ── Regulares ─────────────────────────────────────────────────────
  { inf: 'lernen', pt: 'aprender', type: 'regular', praesens: ['lerne', 'lernst', 'lernt', 'lernen', 'lernt', 'lernen'], partizip: 'gelernt', aux: 'haben' },
  { inf: 'machen', pt: 'fazer', type: 'regular', praesens: ['mache', 'machst', 'macht', 'machen', 'macht', 'machen'], partizip: 'gemacht', aux: 'haben' },
  { inf: 'wohnen', pt: 'morar', type: 'regular', praesens: ['wohne', 'wohnst', 'wohnt', 'wohnen', 'wohnt', 'wohnen'], partizip: 'gewohnt', aux: 'haben' },
  { inf: 'kaufen', pt: 'comprar', type: 'regular', praesens: ['kaufe', 'kaufst', 'kauft', 'kaufen', 'kauft', 'kaufen'], partizip: 'gekauft', aux: 'haben' },
  { inf: 'spielen', pt: 'jogar, brincar', type: 'regular', praesens: ['spiele', 'spielst', 'spielt', 'spielen', 'spielt', 'spielen'], partizip: 'gespielt', aux: 'haben' },
  { inf: 'arbeiten', pt: 'trabalhar', type: 'regular', praesens: ['arbeite', 'arbeitest', 'arbeitet', 'arbeiten', 'arbeitet', 'arbeiten'], partizip: 'gearbeitet', aux: 'haben', note: '-t- pede "e" extra: du arbeitest' },
  { inf: 'hören', pt: 'ouvir', type: 'regular', praesens: ['höre', 'hörst', 'hört', 'hören', 'hört', 'hören'], partizip: 'gehört', aux: 'haben' },
  { inf: 'tanzen', pt: 'dançar', type: 'regular', praesens: ['tanze', 'tanzt', 'tanzt', 'tanzen', 'tanzt', 'tanzen'], partizip: 'getanzt', aux: 'haben' },
  { inf: 'reisen', pt: 'viajar', type: 'regular', praesens: ['reise', 'reist', 'reist', 'reisen', 'reist', 'reisen'], partizip: 'gereist', aux: 'sein' },
  { inf: 'brauchen', pt: 'precisar de', type: 'regular', praesens: ['brauche', 'brauchst', 'braucht', 'brauchen', 'braucht', 'brauchen'], partizip: 'gebraucht', aux: 'haben', note: '"Ich brauche eine Jacke."' },
  { inf: 'suchen', pt: 'procurar', type: 'regular', praesens: ['suche', 'suchst', 'sucht', 'suchen', 'sucht', 'suchen'], partizip: 'gesucht', aux: 'haben', note: '"Er sucht einen neuen Job."' },
  { inf: 'kosten', pt: 'custar', type: 'regular', praesens: ['koste', 'kostest', 'kostet', 'kosten', 'kostet', 'kosten'], partizip: 'gekostet', aux: 'haben', note: '-t- pede "e" extra. Quase sempre na 3ª pessoa: "Was kostet das?"' },
  { inf: 'fragen', pt: 'perguntar', type: 'regular', praesens: ['frage', 'fragst', 'fragt', 'fragen', 'fragt', 'fragen'], partizip: 'gefragt', aux: 'haben', note: '"Ich frage den Lehrer."' },
  { inf: 'sagen', pt: 'dizer', type: 'regular', praesens: ['sage', 'sagst', 'sagt', 'sagen', 'sagt', 'sagen'], partizip: 'gesagt', aux: 'haben', note: '"Wie sagt man das auf Deutsch?"' },
  { inf: 'zeigen', pt: 'mostrar', type: 'regular', praesens: ['zeige', 'zeigst', 'zeigt', 'zeigen', 'zeigt', 'zeigen'], partizip: 'gezeigt', aux: 'haben', note: '"Ich zeige dir die Stadt."' },
  { inf: 'schicken', pt: 'enviar, mandar', type: 'regular', praesens: ['schicke', 'schickst', 'schickt', 'schicken', 'schickt', 'schicken'], partizip: 'geschickt', aux: 'haben', note: '"Ich schicke dir eine Nachricht."' },
  { inf: 'kochen', pt: 'cozinhar', type: 'regular', praesens: ['koche', 'kochst', 'kocht', 'kochen', 'kocht', 'kochen'], partizip: 'gekocht', aux: 'haben', note: '"Meine Großmutter kocht sehr gut."' },
  { inf: 'duschen', pt: 'tomar banho (de chuveiro)', type: 'regular', praesens: ['dusche', 'duschst', 'duscht', 'duschen', 'duscht', 'duschen'], partizip: 'geduscht', aux: 'haben', note: '"Ich dusche jeden Morgen."' },
  { inf: 'putzen', pt: 'limpar', type: 'regular', praesens: ['putze', 'putzt', 'putzt', 'putzen', 'putzt', 'putzen'], partizip: 'geputzt', aux: 'haben', note: 'Radical em -z: du putzt (não "putzst"). "Ich putze die Wohnung."' },
  { inf: 'bezahlen', pt: 'pagar', type: 'regular', praesens: ['bezahle', 'bezahlst', 'bezahlt', 'bezahlen', 'bezahlt', 'bezahlen'], partizip: 'bezahlt', aux: 'haben', note: 'INSEPARÁVEL (be-) → Partizip SEM ge-: bezahlt. Também existe zahlen (gezahlt): "Zahlen, bitte!"' },
  { inf: 'bestellen', pt: 'pedir (comida)', type: 'regular', praesens: ['bestelle', 'bestellst', 'bestellt', 'bestellen', 'bestellt', 'bestellen'], partizip: 'bestellt', aux: 'haben', note: 'INSEPARÁVEL (be-) → Partizip SEM ge-: bestellt. "Wir bestellen zwei Kaffee."' },
  { inf: 'besuchen', pt: 'visitar', type: 'regular', praesens: ['besuche', 'besuchst', 'besucht', 'besuchen', 'besucht', 'besuchen'], partizip: 'besucht', aux: 'haben', note: 'INSEPARÁVEL (be-) → Partizip SEM ge-: besucht. "Ich besuche meine Oma."' },
  { inf: 'erklären', pt: 'explicar', type: 'regular', praesens: ['erkläre', 'erklärst', 'erklärt', 'erklären', 'erklärt', 'erklären'], partizip: 'erklärt', aux: 'haben', note: 'INSEPARÁVEL (er-) → Partizip SEM ge-: erklärt. "Der Lehrer erklärt die Grammatik."' },

  // ── Separáveis ────────────────────────────────────────────────────
  { inf: 'aufstehen', pt: 'levantar-se', type: 'separable', praesens: ['stehe … auf', 'stehst … auf', 'steht … auf', 'stehen … auf', 'steht … auf', 'stehen … auf'], partizip: 'aufgestanden', aux: 'sein', note: 'Ich stehe um sieben auf.' },
  { inf: 'einkaufen', pt: 'fazer compras', type: 'separable', praesens: ['kaufe … ein', 'kaufst … ein', 'kauft … ein', 'kaufen … ein', 'kauft … ein', 'kaufen … ein'], partizip: 'eingekauft', aux: 'haben', note: 'Wir kaufen im Supermarkt ein.' },
  { inf: 'fernsehen', pt: 'ver TV', type: 'separable', praesens: ['sehe … fern', 'siehst … fern', 'sieht … fern', 'sehen … fern', 'seht … fern', 'sehen … fern'], partizip: 'ferngesehen', aux: 'haben', note: 'Abends sehe ich fern.' },
  { inf: 'anrufen', pt: 'telefonar', type: 'separable', praesens: ['rufe … an', 'rufst … an', 'ruft … an', 'rufen … an', 'ruft … an', 'rufen … an'], partizip: 'angerufen', aux: 'haben', note: 'Ich rufe dich morgen an.' },
  { inf: 'mitkommen', pt: 'vir junto', type: 'separable', praesens: ['komme … mit', 'kommst … mit', 'kommt … mit', 'kommen … mit', 'kommt … mit', 'kommen … mit'], partizip: 'mitgekommen', aux: 'sein', note: 'Kommst du mit?' },
  { inf: 'abholen', pt: 'buscar (alguém)', type: 'separable', praesens: ['hole … ab', 'holst … ab', 'holt … ab', 'holen … ab', 'holt … ab', 'holen … ab'], partizip: 'abgeholt', aux: 'haben', note: 'Ich hole dich am Bahnhof ab.' },
  { inf: 'mitbringen', pt: 'trazer junto', type: 'separable', praesens: ['bringe … mit', 'bringst … mit', 'bringt … mit', 'bringen … mit', 'bringt … mit', 'bringen … mit'], partizip: 'mitgebracht', aux: 'haben', note: 'Partizip irregular: mitgebracht. "Ich bringe einen Kuchen mit."' },
  { inf: 'einladen', pt: 'convidar', type: 'separable', praesens: ['lade … ein', 'lädst … ein', 'lädt … ein', 'laden … ein', 'ladet … ein', 'laden … ein'], partizip: 'eingeladen', aux: 'haben', note: 'a→ä no du/er: du lädst … ein! "Ich lade dich zum Geburtstag ein."' },
  { inf: 'aufräumen', pt: 'arrumar', type: 'separable', praesens: ['räume … auf', 'räumst … auf', 'räumt … auf', 'räumen … auf', 'räumt … auf', 'räumen … auf'], partizip: 'aufgeräumt', aux: 'haben', note: 'Ich räume mein Zimmer auf.' },
  { inf: 'anfangen', pt: 'começar', type: 'separable', praesens: ['fange … an', 'fängst … an', 'fängt … an', 'fangen … an', 'fangt … an', 'fangen … an'], partizip: 'angefangen', aux: 'haben', note: 'a→ä no du/er: "Der Film fängt um acht an."' },
  { inf: 'aufhören', pt: 'parar (de fazer algo)', type: 'separable', praesens: ['höre … auf', 'hörst … auf', 'hört … auf', 'hören … auf', 'hört … auf', 'hören … auf'], partizip: 'aufgehört', aux: 'haben', note: 'Hör auf! (Para com isso!)' },
  { inf: 'aufmachen', pt: 'abrir', type: 'separable', praesens: ['mache … auf', 'machst … auf', 'macht … auf', 'machen … auf', 'macht … auf', 'machen … auf'], partizip: 'aufgemacht', aux: 'haben', note: 'Machst du bitte das Fenster auf?' },
  { inf: 'zumachen', pt: 'fechar', type: 'separable', praesens: ['mache … zu', 'machst … zu', 'macht … zu', 'machen … zu', 'macht … zu', 'machen … zu'], partizip: 'zugemacht', aux: 'haben', note: 'Mach bitte die Tür zu!' },
  { inf: 'aussteigen', pt: 'descer (do veículo)', type: 'separable', praesens: ['steige … aus', 'steigst … aus', 'steigt … aus', 'steigen … aus', 'steigt … aus', 'steigen … aus'], partizip: 'ausgestiegen', aux: 'sein', note: 'Wir steigen am Bahnhof aus.' },
  { inf: 'einsteigen', pt: 'entrar (no veículo)', type: 'separable', praesens: ['steige … ein', 'steigst … ein', 'steigt … ein', 'steigen … ein', 'steigt … ein', 'steigen … ein'], partizip: 'eingestiegen', aux: 'sein', note: 'Bitte einsteigen! Der Zug fährt ab.' },
  { inf: 'umsteigen', pt: 'fazer baldeação, trocar de veículo', type: 'separable', praesens: ['steige … um', 'steigst … um', 'steigt … um', 'steigen … um', 'steigt … um', 'steigen … um'], partizip: 'umgestiegen', aux: 'sein', note: 'Ich steige am Hauptbahnhof um.' },
]

export const VERB_TYPES: { id: Verb['type']; label: string; desc: string }[] = [
  { id: 'modal', label: 'Modais', desc: 'können, dürfen, möchten, wollen, müssen, sollen' },
  { id: 'regular', label: 'Regulares', desc: 'radical + e/st/t/en/t/en' },
  { id: 'irregular', label: 'Irregulares', desc: 'mudam a vogal no du/er' },
  { id: 'separable', label: 'Separáveis', desc: 'prefixo vai para o fim da frase' },
]
