import type { VocabCard } from './types'

// Baralho SRS — vocabulário A1.1 + A1.2, ancorado nas aulas reais
// (DEUTSCHUNTERRICHT 11 e 13) e nos temas do vault Obsidian.
// id estável = nunca renomear (o agendamento SRS aponta para ele).

const c = (
  id: string,
  de: string,
  pt: string,
  extra: Partial<VocabCard> & { tags: string[]; level: VocabCard['level'] },
): VocabCard => ({ id, de, pt, ...extra })

export const VOCAB: VocabCard[] = [
  // ── Lugares da cidade (die Lokale — aula 13) ──────────────────────
  c('lok-schule', 'Schule', 'escola', { artikel: 'die', plural: 'Schulen', example: 'Ich gehe in die Schule.', tags: ['lugares'], level: 'a12' }),
  c('lok-apotheke', 'Apotheke', 'farmácia', { artikel: 'die', plural: 'Apotheken', example: 'Die Apotheke ist neben der Bank.', tags: ['lugares'], level: 'a12' }),
  c('lok-bank', 'Bank', 'banco', { artikel: 'die', plural: 'Banken', example: 'Ich muss zur Bank gehen.', tags: ['lugares'], level: 'a12' }),
  c('lok-haltestelle', 'Haltestelle', 'ponto de ônibus', { artikel: 'die', plural: 'Haltestellen', example: 'Wir warten an der Haltestelle.', tags: ['lugares'], level: 'a12' }),
  c('lok-baeckerei', 'Bäckerei', 'padaria', { artikel: 'die', plural: 'Bäckereien', example: 'Gehen wir zur Bäckerei?', tags: ['lugares'], level: 'a12' }),
  c('lok-kirche', 'Kirche', 'igreja', { artikel: 'die', plural: 'Kirchen', example: 'Die Kirche ist alt.', tags: ['lugares'], level: 'a12' }),
  c('lok-tankstelle', 'Tankstelle', 'posto de gasolina', { artikel: 'die', plural: 'Tankstellen', example: 'Er fährt zur Tankstelle.', tags: ['lugares'], level: 'a12' }),
  c('lok-kneipe', 'Kneipe', 'bar, boteco', { artikel: 'die', plural: 'Kneipen', example: 'Wir gehen in die Kneipe.', tags: ['lugares'], level: 'a12' }),
  c('lok-post', 'Post', 'correio', { artikel: 'die', example: 'Ich gehe zur Post.', tags: ['lugares'], level: 'a12' }),
  c('lok-disko', 'Disko', 'balada, discoteca', { artikel: 'die', plural: 'Diskos', example: 'Geht ihr gern in die Disko?', tags: ['lugares'], level: 'a12' }),
  c('lok-fabrik', 'Fabrik', 'fábrica', { artikel: 'die', plural: 'Fabriken', example: 'Mein Vater arbeitet in der Fabrik.', tags: ['lugares'], level: 'a12' }),
  c('lok-praxis', 'Praxis', 'consultório', { artikel: 'die', plural: 'Praxen', example: 'Die Praxis ist heute geschlossen.', tags: ['lugares'], level: 'a12' }),
  c('lok-supermarkt', 'Supermarkt', 'supermercado', { artikel: 'der', plural: 'Supermärkte', example: 'Ich gehe zum Supermarkt.', tags: ['lugares'], level: 'a12' }),
  c('lok-bahnhof', 'Bahnhof', 'estação de trem', { artikel: 'der', plural: 'Bahnhöfe', example: 'Der Zug ist am Bahnhof.', tags: ['lugares'], level: 'a12' }),
  c('lok-markt', 'Markt', 'mercado, feira', { artikel: 'der', plural: 'Märkte', example: 'Samstags gehe ich zum Markt.', tags: ['lugares'], level: 'a12' }),
  c('lok-flohmarkt', 'Flohmarkt', 'feira de usados', { artikel: 'der', plural: 'Flohmärkte', example: 'Der Flohmarkt ist am Sonntag.', tags: ['lugares'], level: 'a12' }),
  c('lok-platz', 'Platz', 'praça', { artikel: 'der', plural: 'Plätze', example: 'Kinder spielen auf dem Platz.', tags: ['lugares'], level: 'a12' }),
  c('lok-garten', 'Garten', 'jardim', { artikel: 'der', plural: 'Gärten', example: 'Der Garten ist schön.', tags: ['lugares'], level: 'a12' }),
  c('lok-zoo', 'Zoo', 'zoológico', { artikel: 'der', plural: 'Zoos', example: 'Wir fahren in den Zoo.', tags: ['lugares'], level: 'a12' }),
  c('lok-zirkus', 'Zirkus', 'circo', { artikel: 'der', plural: 'Zirkusse', example: 'Der Zirkus ist in der Stadt.', tags: ['lugares'], level: 'a12' }),
  c('lok-imbissstand', 'Imbissstand', 'barraca de lanche', { artikel: 'der', plural: 'Imbissstände', example: 'Ich esse am Imbissstand.', tags: ['lugares'], level: 'a12' }),
  c('lok-bauernhof', 'Bauernhof', 'fazenda, sítio', { artikel: 'der', plural: 'Bauernhöfe', example: 'Oma wohnt auf dem Bauernhof.', tags: ['lugares'], level: 'a12' }),
  c('lok-kino', 'Kino', 'cinema', { artikel: 'das', plural: 'Kinos', example: 'Wann gehst du ins Kino?', tags: ['lugares'], level: 'a12' }),
  c('lok-theater', 'Theater', 'teatro', { artikel: 'das', plural: 'Theater', example: 'Wir gehen heute ins Theater.', tags: ['lugares'], level: 'a12' }),
  c('lok-restaurant', 'Restaurant', 'restaurante', { artikel: 'das', plural: 'Restaurants', example: 'Das Restaurant ist teuer.', tags: ['lugares'], level: 'a12' }),
  c('lok-stadion', 'Stadion', 'estádio', { artikel: 'das', plural: 'Stadien', example: 'Anika möchte ins Stadion gehen.', tags: ['lugares'], level: 'a12' }),
  c('lok-museum', 'Museum', 'museu', { artikel: 'das', plural: 'Museen', example: 'Das Museum öffnet um zehn.', tags: ['lugares'], level: 'a12' }),
  c('lok-hotel', 'Hotel', 'hotel', { artikel: 'das', plural: 'Hotels', example: 'Wir schlafen im Hotel.', tags: ['lugares'], level: 'a12' }),
  c('lok-cafe', 'Café', 'café (lugar)', { artikel: 'das', plural: 'Cafés', example: 'Treffen wir uns im Café?', tags: ['lugares'], level: 'a12' }),
  c('lok-krankenhaus', 'Krankenhaus', 'hospital', { artikel: 'das', plural: 'Krankenhäuser', example: 'Julius muss ins Krankenhaus fahren.', tags: ['lugares'], level: 'a12' }),

  // ── Transporte (Verkehrsmittel — aula 13) ─────────────────────────
  c('vk-auto', 'Auto', 'carro', { artikel: 'das', plural: 'Autos', example: 'Juli fährt mit dem Auto ins Kino.', tags: ['transporte'], level: 'a12' }),
  c('vk-fahrrad', 'Fahrrad', 'bicicleta', { artikel: 'das', plural: 'Fahrräder', example: 'Ich fahre mit dem Fahrrad.', tags: ['transporte'], level: 'a12' }),
  c('vk-flugzeug', 'Flugzeug', 'avião', { artikel: 'das', plural: 'Flugzeuge', example: 'Das Flugzeug fliegt nach Berlin.', tags: ['transporte'], level: 'a12' }),
  c('vk-schiff', 'Schiff', 'navio', { artikel: 'das', plural: 'Schiffe', example: 'Wir reisen mit dem Schiff.', tags: ['transporte'], level: 'a12' }),
  c('vk-motorrad', 'Motorrad', 'moto', { artikel: 'das', plural: 'Motorräder', example: 'Er fährt Motorrad.', tags: ['transporte'], level: 'a12' }),
  c('vk-bus', 'Bus', 'ônibus', { artikel: 'der', plural: 'Busse', example: 'Ich fahre mit dem Bus zur Arbeit.', tags: ['transporte'], level: 'a12' }),
  c('vk-zug', 'Zug', 'trem', { artikel: 'der', plural: 'Züge', example: 'Der Zug kommt um acht.', tags: ['transporte'], level: 'a12' }),
  c('vk-ubahn', 'U-Bahn', 'metrô', { artikel: 'die', plural: 'U-Bahnen', example: 'Ich fahre mit der U-Bahn.', tags: ['transporte'], level: 'a12' }),
  c('vk-bahn', 'Bahn', 'trem, ferrovia', { artikel: 'die', plural: 'Bahnen', example: 'Wir fahren mit der Bahn.', tags: ['transporte'], level: 'a12' }),
  c('vk-zufuss', 'zu Fuß', 'a pé', { example: 'Wir gehen zu Fuß zum Park.', tags: ['transporte'], level: 'a12' }),

  // ── Cores (die Farben — aula 11) ──────────────────────────────────
  c('fb-rot', 'rot', 'vermelho', { example: 'Das Auto ist rot.', tags: ['cores'], level: 'a12' }),
  c('fb-blau', 'blau', 'azul', { example: 'Der Himmel ist blau.', tags: ['cores'], level: 'a12' }),
  c('fb-gelb', 'gelb', 'amarelo', { example: 'Die Banane ist gelb.', tags: ['cores'], level: 'a12' }),
  c('fb-gruen', 'grün', 'verde', { example: 'Der Apfel ist grün.', tags: ['cores'], level: 'a12' }),
  c('fb-schwarz', 'schwarz', 'preto', { example: 'Die Katze ist schwarz.', tags: ['cores'], level: 'a12' }),
  c('fb-weiss', 'weiß', 'branco', { example: 'Der Schnee ist weiß.', tags: ['cores'], level: 'a12' }),
  c('fb-grau', 'grau', 'cinza', { example: 'Die Maus ist grau.', tags: ['cores'], level: 'a12' }),
  c('fb-braun', 'braun', 'marrom', { example: 'Der Bär ist braun.', tags: ['cores'], level: 'a12' }),
  c('fb-rosa', 'rosa', 'rosa (claro)', { example: 'Die Blume ist rosa.', tags: ['cores'], level: 'a12' }),
  c('fb-lila', 'lila', 'roxo, lilás', { example: 'Meine Lieblingsfarbe ist lila.', tags: ['cores'], level: 'a12' }),
  c('fb-orange', 'orange', 'laranja (cor)', { example: 'Die Orange ist orange.', tags: ['cores'], level: 'a12' }),
  c('fb-bunt', 'bunt', 'colorido', { example: 'Der Regenbogen ist bunt.', tags: ['cores'], level: 'a12' }),
  c('fb-lieblingsfarbe', 'Lieblingsfarbe', 'cor favorita', { artikel: 'die', example: 'Was ist deine Lieblingsfarbe?', tags: ['cores'], level: 'a12' }),
  c('fb-regenbogen', 'Regenbogen', 'arco-íris', { artikel: 'der', example: 'Der Regenbogen hat viele Farben.', tags: ['cores'], level: 'a12' }),

  // ── Palavrinhas da aula 11 (man / mal / pro) ──────────────────────
  c('w-man', 'man', '"a gente", se (impessoal)', { example: 'Man darf nicht in der Klasse essen.', tags: ['gramatica'], level: 'a12' }),
  c('w-einmal', 'einmal', 'uma vez', { example: 'Ich trainiere einmal pro Woche.', tags: ['gramatica'], level: 'a12' }),
  c('w-pro', 'pro', 'por (frequência)', { example: 'Zweimal pro Monat.', tags: ['gramatica'], level: 'a12' }),
  c('w-empfehlen', 'empfehlen', 'recomendar', { example: 'Ich empfehle dir diesen Film.', tags: ['verbos'], level: 'a12' }),
  c('w-ratschlag', 'Ratschlag', 'conselho', { artikel: 'der', plural: 'Ratschläge', example: 'Der Arzt gibt mir einen Ratschlag.', tags: ['gramatica'], level: 'a12' }),

  // ── Básicos A1.1 — família ────────────────────────────────────────
  c('fam-mutter', 'Mutter', 'mãe', { artikel: 'die', plural: 'Mütter', example: 'Meine Mutter heißt Ana.', tags: ['familia'], level: 'a11' }),
  c('fam-vater', 'Vater', 'pai', { artikel: 'der', plural: 'Väter', example: 'Mein Vater arbeitet viel.', tags: ['familia'], level: 'a11' }),
  c('fam-bruder', 'Bruder', 'irmão', { artikel: 'der', plural: 'Brüder', example: 'Ich habe einen Bruder.', tags: ['familia'], level: 'a11' }),
  c('fam-schwester', 'Schwester', 'irmã', { artikel: 'die', plural: 'Schwestern', example: 'Meine Schwester ist jung.', tags: ['familia'], level: 'a11' }),
  c('fam-eltern', 'Eltern', 'pais (pai e mãe)', { artikel: 'die', example: 'Meine Eltern wohnen in Brasilien.', tags: ['familia'], level: 'a11' }),
  c('fam-kind', 'Kind', 'criança, filho(a)', { artikel: 'das', plural: 'Kinder', example: 'Das Kind spielt im Garten.', tags: ['familia'], level: 'a11' }),
  c('fam-familie', 'Familie', 'família', { artikel: 'die', plural: 'Familien', example: 'Meine Familie ist groß.', tags: ['familia'], level: 'a11' }),
  c('fam-grossmutter', 'Großmutter', 'avó', { artikel: 'die', plural: 'Großmütter', example: 'Meine Großmutter kocht gut.', tags: ['familia'], level: 'a11' }),

  // ── Básicos A1.1 — comida/bebida ──────────────────────────────────
  c('es-brot', 'Brot', 'pão', { artikel: 'das', plural: 'Brote', example: 'Ich möchte ein Brot, bitte.', tags: ['comida'], level: 'a11' }),
  c('es-wasser', 'Wasser', 'água', { artikel: 'das', example: 'Darf ich bitte Wasser trinken?', tags: ['comida'], level: 'a11' }),
  c('es-kaffee', 'Kaffee', 'café (bebida)', { artikel: 'der', example: 'Ich trinke morgens Kaffee.', tags: ['comida'], level: 'a11' }),
  c('es-milch', 'Milch', 'leite', { artikel: 'die', example: 'Die Milch ist kalt.', tags: ['comida'], level: 'a11' }),
  c('es-apfel', 'Apfel', 'maçã', { artikel: 'der', plural: 'Äpfel', example: 'Der Apfel schmeckt gut.', tags: ['comida'], level: 'a11' }),
  c('es-kaese', 'Käse', 'queijo', { artikel: 'der', example: 'Ich esse Brot mit Käse.', tags: ['comida'], level: 'a11' }),
  c('es-fruehstueck', 'Frühstück', 'café da manhã', { artikel: 'das', example: 'Das Frühstück ist fertig.', tags: ['comida'], level: 'a11' }),
  c('es-hunger', 'Hunger', 'fome', { artikel: 'der', example: 'Ich habe Hunger.', tags: ['comida'], level: 'a11' }),

  // ── Básicos A1.1 — tempo/rotina ───────────────────────────────────
  c('zt-heute', 'heute', 'hoje', { example: 'Heute lerne ich Deutsch.', tags: ['tempo'], level: 'a11' }),
  c('zt-morgen', 'morgen', 'amanhã', { example: 'Morgen habe ich eine Prüfung.', tags: ['tempo'], level: 'a11' }),
  c('zt-gestern', 'gestern', 'ontem', { example: 'Gestern war Montag.', tags: ['tempo'], level: 'a11' }),
  c('zt-jetzt', 'jetzt', 'agora', { example: 'Jetzt ist es fünf nach fünf.', tags: ['tempo'], level: 'a11' }),
  c('zt-woche', 'Woche', 'semana', { artikel: 'die', plural: 'Wochen', example: 'Einmal pro Woche.', tags: ['tempo'], level: 'a11' }),
  c('zt-wochenende', 'Wochenende', 'fim de semana', { artikel: 'das', example: 'Am Wochenende gehen wir zu Fuß.', tags: ['tempo'], level: 'a11' }),
  c('zt-uhr', 'Uhr', 'relógio; horas', { artikel: 'die', plural: 'Uhren', example: 'Wie viel Uhr ist es?', tags: ['tempo'], level: 'a11' }),
  c('zt-pruefung', 'Prüfung', 'prova, exame', { artikel: 'die', plural: 'Prüfungen', example: 'Ich muss für die Prüfung lernen.', tags: ['tempo'], level: 'a11' }),

  // ── Básicos A1.1 — pessoas/perfil (Vorstellen — aula 13) ──────────
  c('vs-name', 'Name', 'nome', { artikel: 'der', plural: 'Namen', example: 'Mein Name ist Lucas.', tags: ['apresentacao'], level: 'a11' }),
  c('vs-alter', 'Alter', 'idade', { artikel: 'das', example: 'Ich bin 25 Jahre alt.', tags: ['apresentacao'], level: 'a11' }),
  c('vs-land', 'Land', 'país', { artikel: 'das', plural: 'Länder', example: 'Ich komme aus Brasilien.', tags: ['apresentacao'], level: 'a11' }),
  c('vs-wohnort', 'Wohnort', 'cidade onde mora', { artikel: 'der', example: 'Mein Wohnort ist São Paulo.', tags: ['apresentacao'], level: 'a11' }),
  c('vs-sprache', 'Sprache', 'língua, idioma', { artikel: 'die', plural: 'Sprachen', example: 'Ich spreche zwei Sprachen.', tags: ['apresentacao'], level: 'a11' }),
  c('vs-hobby', 'Hobby', 'hobby', { artikel: 'das', plural: 'Hobbys', example: 'Meine Hobbys sind Sport und Musik.', tags: ['apresentacao'], level: 'a11' }),
  c('vs-haustier', 'Haustier', 'animal de estimação', { artikel: 'das', plural: 'Haustiere', example: 'Hast du ein Haustier?', tags: ['apresentacao'], level: 'a11' }),
  c('vs-beruf', 'Beruf', 'profissão', { artikel: 'der', plural: 'Berufe', example: 'Was bist du von Beruf?', tags: ['apresentacao'], level: 'a11' }),
  c('vs-telefonnummer', 'Telefonnummer', 'número de telefone', { artikel: 'die', example: 'Wie ist deine Telefonnummer?', tags: ['apresentacao'], level: 'a11' }),
  c('vs-unterricht', 'Unterricht', 'aula', { artikel: 'der', example: 'Der Deutschunterricht beginnt um acht.', tags: ['apresentacao'], level: 'a11' }),

  // ── Verbos-chave (aparecem nos módulos) ───────────────────────────
  c('vb-lernen', 'lernen', 'aprender, estudar', { example: 'Ich muss heute lernen.', tags: ['verbos'], level: 'a11' }),
  c('vb-sprechen', 'sprechen', 'falar', { example: 'Kannst du Deutsch sprechen?', tags: ['verbos'], level: 'a11' }),
  c('vb-fahren', 'fahren', 'ir (de veículo), dirigir', { example: 'Kannst du Auto fahren?', tags: ['verbos'], level: 'a11' }),
  c('vb-fliegen', 'fliegen', 'voar, ir de avião', { example: 'Elio fliegt in die Schweiz.', tags: ['verbos'], level: 'a11' }),
  c('vb-reisen', 'reisen', 'viajar', { example: 'Daniel will nach Deutschland reisen.', tags: ['verbos'], level: 'a11' }),
  c('vb-tanzen', 'tanzen', 'dançar', { example: 'Thomas kann sehr gut tanzen.', tags: ['verbos'], level: 'a11' }),
  c('vb-bleiben', 'bleiben', 'ficar, permanecer', { example: 'Sie soll zu Hause bleiben.', tags: ['verbos'], level: 'a11' }),
  c('vb-arbeiten', 'arbeiten', 'trabalhar', { example: 'Ich arbeite von neun bis fünf.', tags: ['verbos'], level: 'a11' }),
  c('vb-kaufen', 'kaufen', 'comprar', { example: 'Ich kaufe Brot in der Bäckerei.', tags: ['verbos'], level: 'a11' }),
  c('vb-helfen', 'helfen', 'ajudar (+ Dativ)', { example: 'Kannst du mir helfen?', tags: ['verbos'], level: 'a12' }),
  c('vb-gefallen', 'gefallen', 'agradar (+ Dativ)', { example: 'Das Bild gefällt mir.', tags: ['verbos'], level: 'a12' }),
  c('vb-gehoeren', 'gehören', 'pertencer (+ Dativ)', { example: 'Das Auto gehört meinem Vater.', tags: ['verbos'], level: 'a12' }),
  c('vb-schmecken', 'schmecken', 'ter gosto, agradar ao paladar (+ Dativ)', { example: 'Die Pizza schmeckt mir.', tags: ['verbos'], level: 'a12' }),
  c('vb-aufstehen', 'aufstehen', 'levantar-se (separável)', { example: 'Ich stehe um sieben auf.', tags: ['verbos'], level: 'a12' }),
  c('vb-einkaufen', 'einkaufen', 'fazer compras (separável)', { example: 'Wir kaufen im Supermarkt ein.', tags: ['verbos'], level: 'a12' }),
  c('vb-fernsehen', 'fernsehen', 'ver TV (separável)', { example: 'Abends sehe ich fern.', tags: ['verbos'], level: 'a12' }),
  c('vb-anrufen', 'anrufen', 'ligar, telefonar (separável)', { example: 'Ich rufe dich morgen an.', tags: ['verbos'], level: 'a12' }),
  c('vb-abholen', 'abholen', 'buscar (alguém) (separável)', { example: 'Ich hole dich am Bahnhof ab.', tags: ['verbos'], level: 'a12' }),

  // ── Fórmulas úteis (frases feitas) ────────────────────────────────
  c('fr-wiegehts', "Wie geht's?", 'Como vai?', { example: "Hallo! Wie geht's?", tags: ['frases'], level: 'a11' }),
  c('fr-woherkommst', 'Woher kommst du?', 'De onde você vem?', { tags: ['frases'], level: 'a11' }),
  c('fr-wohin', 'Wohin gehst du?', 'Aonde você vai?', { tags: ['frases'], level: 'a12' }),
  c('fr-wiespaet', 'Wie spät ist es?', 'Que horas são?', { tags: ['frases'], level: 'a12' }),
  c('fr-ichmoechte', 'Ich möchte…, bitte.', 'Eu gostaria de…, por favor.', { example: 'Ich möchte ein Brot, bitte.', tags: ['frases'], level: 'a12' }),
  c('fr-darfich', 'Darf ich…?', 'Posso…? (permissão)', { example: 'Darf ich bitte Wasser trinken?', tags: ['frases'], level: 'a12' }),
  c('fr-keineahnung', 'Keine Ahnung.', 'Não faço ideia.', { tags: ['frases'], level: 'a11' }),
  c('fr-nochmal', 'Noch einmal, bitte.', 'Mais uma vez, por favor.', { tags: ['frases'], level: 'a11' }),

  // ── Profissões (die Berufe) ───────────────────────────────────────
  c('bf-lehrer', 'Lehrer', 'professor (die Lehrerin = professora)', { artikel: 'der', plural: 'Lehrer', example: 'Mein Lehrer kommt aus Berlin.', tags: ['berufe'], level: 'a11' }),
  c('bf-arzt', 'Arzt', 'médico (die Ärztin = médica)', { artikel: 'der', plural: 'Ärzte', example: 'Der Arzt arbeitet im Krankenhaus.', tags: ['berufe'], level: 'a11' }),
  c('bf-ingenieur', 'Ingenieur', 'engenheiro', { artikel: 'der', plural: 'Ingenieure', example: 'Mein Bruder ist Ingenieur.', tags: ['berufe'], level: 'a11' }),
  c('bf-verkaeufer', 'Verkäufer', 'vendedor', { artikel: 'der', plural: 'Verkäufer', example: 'Der Verkäufer ist sehr nett.', tags: ['berufe'], level: 'a11' }),
  c('bf-koch', 'Koch', 'cozinheiro', { artikel: 'der', plural: 'Köche', example: 'Der Koch arbeitet im Restaurant.', tags: ['berufe'], level: 'a11' }),
  c('bf-kellner', 'Kellner', 'garçom', { artikel: 'der', plural: 'Kellner', example: 'Der Kellner bringt die Speisekarte.', tags: ['berufe'], level: 'a11' }),
  c('bf-student', 'Student', 'estudante universitário', { artikel: 'der', plural: 'Studenten', example: 'Ich bin Student und lerne Deutsch.', tags: ['berufe'], level: 'a11' }),
  c('bf-entwickler', 'Entwickler', 'desenvolvedor (der Programmierer = programador)', { artikel: 'der', plural: 'Entwickler', example: 'Lucas arbeitet als Entwickler.', tags: ['berufe'], level: 'a11' }),
  c('bf-polizist', 'Polizist', 'policial', { artikel: 'der', plural: 'Polizisten', example: 'Der Polizist steht an der Haltestelle.', tags: ['berufe'], level: 'a11' }),
  c('bf-friseur', 'Friseur', 'cabeleireiro', { artikel: 'der', plural: 'Friseure', example: 'Ich gehe morgen zum Friseur.', tags: ['berufe'], level: 'a11' }),
  c('bf-krankenschwester', 'Krankenschwester', 'enfermeira (der Krankenpfleger = enfermeiro)', { artikel: 'die', plural: 'Krankenschwestern', example: 'Die Krankenschwester arbeitet im Krankenhaus.', tags: ['berufe'], level: 'a11' }),
  c('bf-arbeiten-als', 'arbeiten als', 'trabalhar como', { example: 'Ich arbeite als Kellner.', tags: ['berufe'], level: 'a11' }),
  c('bf-job', 'Job', 'emprego, trampo', { artikel: 'der', plural: 'Jobs', example: 'Er sucht einen neuen Job.', tags: ['berufe'], level: 'a11' }),
  c('bf-firma', 'Firma', 'empresa, firma', { artikel: 'die', plural: 'Firmen', example: 'Die Firma ist in München.', tags: ['berufe'], level: 'a11' }),
  c('bf-buero', 'Büro', 'escritório', { artikel: 'das', plural: 'Büros', example: 'Ich arbeite im Büro.', tags: ['berufe'], level: 'a11' }),

  // ── Países & línguas (Länder & Sprachen) ──────────────────────────
  c('ld-deutschland', 'Deutschland', 'Alemanha', { example: 'Deutschland liegt in Europa.', tags: ['laender'], level: 'a11' }),
  c('ld-brasilien', 'Brasilien', 'Brasil', { example: 'Ich komme aus Brasilien.', tags: ['laender'], level: 'a11' }),
  c('ld-schweiz', 'Schweiz', 'Suíça (sempre com artigo: die Schweiz)', { artikel: 'die', example: 'Elio fliegt in die Schweiz.', tags: ['laender'], level: 'a11' }),
  c('ld-oesterreich', 'Österreich', 'Áustria', { example: 'Wien liegt in Österreich.', tags: ['laender'], level: 'a11' }),
  c('ld-usa', 'USA', 'EUA (sempre plural: die USA)', { artikel: 'die', example: 'Meine Tante wohnt in den USA.', tags: ['laender'], level: 'a11' }),
  c('ld-frankreich', 'Frankreich', 'França', { example: 'Paris liegt in Frankreich.', tags: ['laender'], level: 'a11' }),
  c('ld-spanien', 'Spanien', 'Espanha', { example: 'Wir reisen im Sommer nach Spanien.', tags: ['laender'], level: 'a11' }),
  c('ld-portugal', 'Portugal', 'Portugal', { example: 'Ich fliege nach Portugal.', tags: ['laender'], level: 'a11' }),
  c('ld-england', 'England', 'Inglaterra', { example: 'Er kommt aus England.', tags: ['laender'], level: 'a11' }),
  c('ld-tuerkei', 'Türkei', 'Turquia (sempre com artigo: die Türkei)', { artikel: 'die', example: 'Sie fährt in die Türkei.', tags: ['laender'], level: 'a11' }),
  c('ld-deutsch', 'Deutsch', 'alemão (idioma)', { example: 'Ich lerne Deutsch.', tags: ['laender'], level: 'a11' }),
  c('ld-portugiesisch', 'Portugiesisch', 'português (idioma)', { example: 'Wir sprechen Portugiesisch.', tags: ['laender'], level: 'a11' }),
  c('ld-englisch', 'Englisch', 'inglês (idioma)', { example: 'Sprichst du Englisch?', tags: ['laender'], level: 'a11' }),
  c('ld-spanisch', 'Spanisch', 'espanhol (idioma)', { example: 'Sie spricht ein bisschen Spanisch.', tags: ['laender'], level: 'a11' }),
  c('ld-heimat', 'Heimat', 'terra natal', { artikel: 'die', example: 'Brasilien ist meine Heimat.', tags: ['laender'], level: 'a11' }),

  // ── Hobbys & lazer (Hobbys & Freizeit) ────────────────────────────
  c('hb-schwimmen', 'schwimmen', 'nadar', { example: 'Ich schwimme gern im Sommer.', tags: ['hobbys'], level: 'a11' }),
  c('hb-lesen', 'lesen', 'ler', { example: 'Ich lese gern Bücher.', tags: ['hobbys'], level: 'a11' }),
  c('hb-kochen', 'kochen', 'cozinhar', { example: 'Kochst du gern?', tags: ['hobbys'], level: 'a11' }),
  c('hb-fotografieren', 'fotografieren', 'fotografar', { example: 'Ich fotografiere gern in der Stadt.', tags: ['hobbys'], level: 'a11' }),
  c('hb-wandern', 'wandern', 'fazer trilha, caminhar', { example: 'Wir wandern am Wochenende.', tags: ['hobbys'], level: 'a11' }),
  c('hb-zeichnen', 'zeichnen', 'desenhar', { example: 'Meine Schwester zeichnet sehr gut.', tags: ['hobbys'], level: 'a11' }),
  c('hb-musik-hoeren', 'Musik hören', 'ouvir música', { example: 'Ich höre gern Musik.', tags: ['hobbys'], level: 'a11' }),
  c('hb-fussball-spielen', 'Fußball spielen', 'jogar futebol', { example: 'Wir spielen samstags Fußball.', tags: ['hobbys'], level: 'a11' }),
  c('hb-rad-fahren', 'Rad fahren', 'andar de bicicleta', { example: 'Ich fahre gern Rad.', tags: ['hobbys'], level: 'a11' }),
  c('hb-singen', 'singen', 'cantar', { example: 'Sie singt sehr schön.', tags: ['hobbys'], level: 'a11' }),
  c('hb-musik', 'Musik', 'música', { artikel: 'die', example: 'Die Musik ist zu laut.', tags: ['hobbys'], level: 'a11' }),
  c('hb-sport', 'Sport', 'esporte', { artikel: 'der', example: 'Ich mache dreimal pro Woche Sport.', tags: ['hobbys'], level: 'a11' }),
  c('hb-spiel', 'Spiel', 'jogo', { artikel: 'das', plural: 'Spiele', example: 'Das Spiel beginnt um acht.', tags: ['hobbys'], level: 'a11' }),
  c('hb-freizeit', 'Freizeit', 'tempo livre', { artikel: 'die', example: 'Was machst du in deiner Freizeit?', tags: ['hobbys'], level: 'a11' }),

  // ── Casa & móveis (die Wohnung) ───────────────────────────────────
  c('wh-wohnung', 'Wohnung', 'apartamento', { artikel: 'die', plural: 'Wohnungen', example: 'Die Wohnung hat drei Zimmer.', tags: ['wohnung'], level: 'a12' }),
  c('wh-haus', 'Haus', 'casa', { artikel: 'das', plural: 'Häuser', example: 'Das Haus ist groß.', tags: ['wohnung'], level: 'a12' }),
  c('wh-zimmer', 'Zimmer', 'quarto, cômodo', { artikel: 'das', plural: 'Zimmer', example: 'Mein Zimmer ist klein.', tags: ['wohnung'], level: 'a12' }),
  c('wh-kueche', 'Küche', 'cozinha', { artikel: 'die', plural: 'Küchen', example: 'Wir essen in der Küche.', tags: ['wohnung'], level: 'a12' }),
  c('wh-bad', 'Bad', 'banheiro', { artikel: 'das', plural: 'Bäder', example: 'Das Bad ist neben der Küche.', tags: ['wohnung'], level: 'a12' }),
  c('wh-wohnzimmer', 'Wohnzimmer', 'sala de estar', { artikel: 'das', plural: 'Wohnzimmer', example: 'Wir sehen im Wohnzimmer fern.', tags: ['wohnung'], level: 'a12' }),
  c('wh-schlafzimmer', 'Schlafzimmer', 'quarto (de dormir)', { artikel: 'das', plural: 'Schlafzimmer', example: 'Das Schlafzimmer ist ruhig.', tags: ['wohnung'], level: 'a12' }),
  c('wh-tisch', 'Tisch', 'mesa', { artikel: 'der', plural: 'Tische', example: 'Das Buch liegt auf dem Tisch.', tags: ['wohnung'], level: 'a12' }),
  c('wh-stuhl', 'Stuhl', 'cadeira', { artikel: 'der', plural: 'Stühle', example: 'Der Stuhl ist neu.', tags: ['wohnung'], level: 'a12' }),
  c('wh-sofa', 'Sofa', 'sofá', { artikel: 'das', plural: 'Sofas', example: 'Die Katze schläft auf dem Sofa.', tags: ['wohnung'], level: 'a12' }),
  c('wh-bett', 'Bett', 'cama', { artikel: 'das', plural: 'Betten', example: 'Ich gehe um elf ins Bett.', tags: ['wohnung'], level: 'a12' }),
  c('wh-schrank', 'Schrank', 'armário', { artikel: 'der', plural: 'Schränke', example: 'Der Pullover ist im Schrank.', tags: ['wohnung'], level: 'a12' }),
  c('wh-kuehlschrank', 'Kühlschrank', 'geladeira', { artikel: 'der', plural: 'Kühlschränke', example: 'Die Milch ist im Kühlschrank.', tags: ['wohnung'], level: 'a12' }),
  c('wh-lampe', 'Lampe', 'luminária, lâmpada', { artikel: 'die', plural: 'Lampen', example: 'Die Lampe ist an.', tags: ['wohnung'], level: 'a12' }),
  c('wh-fenster', 'Fenster', 'janela', { artikel: 'das', plural: 'Fenster', example: 'Machst du bitte das Fenster auf?', tags: ['wohnung'], level: 'a12' }),
  c('wh-tuer', 'Tür', 'porta', { artikel: 'die', plural: 'Türen', example: 'Die Tür ist zu.', tags: ['wohnung'], level: 'a12' }),
  c('wh-miete', 'Miete', 'aluguel', { artikel: 'die', plural: 'Mieten', example: 'Die Miete ist sehr teuer.', tags: ['wohnung'], level: 'a12' }),

  // ── Roupas (die Kleidung) ─────────────────────────────────────────
  c('kl-pullover', 'Pullover', 'suéter, pulôver', { artikel: 'der', plural: 'Pullover', example: 'Der Pullover ist warm.', tags: ['kleidung'], level: 'a12' }),
  c('kl-hose', 'Hose', 'calça', { artikel: 'die', plural: 'Hosen', example: 'Die Hose ist zu groß.', tags: ['kleidung'], level: 'a12' }),
  c('kl-hemd', 'Hemd', 'camisa', { artikel: 'das', plural: 'Hemden', example: 'Das Hemd ist weiß.', tags: ['kleidung'], level: 'a12' }),
  c('kl-tshirt', 'T-Shirt', 'camiseta', { artikel: 'das', plural: 'T-Shirts', example: 'Ich trage heute ein T-Shirt.', tags: ['kleidung'], level: 'a12' }),
  c('kl-rock', 'Rock', 'saia', { artikel: 'der', plural: 'Röcke', example: 'Der Rock ist rot.', tags: ['kleidung'], level: 'a12' }),
  c('kl-kleid', 'Kleid', 'vestido', { artikel: 'das', plural: 'Kleider', example: 'Das Kleid ist sehr schön.', tags: ['kleidung'], level: 'a12' }),
  c('kl-jacke', 'Jacke', 'jaqueta, casaco leve', { artikel: 'die', plural: 'Jacken', example: 'Ich brauche eine Jacke.', tags: ['kleidung'], level: 'a12' }),
  c('kl-mantel', 'Mantel', 'casaco, sobretudo', { artikel: 'der', plural: 'Mäntel', example: 'Im Winter trage ich einen Mantel.', tags: ['kleidung'], level: 'a12' }),
  c('kl-schuhe', 'Schuhe', 'sapatos (Pl.; singular: der Schuh)', { artikel: 'die', example: 'Die Schuhe sind neu.', tags: ['kleidung'], level: 'a12' }),
  c('kl-socken', 'Socken', 'meias (Pl.; singular: die Socke)', { artikel: 'die', example: 'Die Socken sind schwarz.', tags: ['kleidung'], level: 'a12' }),
  c('kl-hut', 'Hut', 'chapéu', { artikel: 'der', plural: 'Hüte', example: 'Der Hut ist alt.', tags: ['kleidung'], level: 'a12' }),
  c('kl-brille', 'Brille', 'óculos (singular em alemão!)', { artikel: 'die', plural: 'Brillen', example: 'Wo ist meine Brille?', tags: ['kleidung'], level: 'a12' }),
  c('kl-groesse', 'Größe', 'tamanho', { artikel: 'die', plural: 'Größen', example: 'Welche Größe haben Sie?', tags: ['kleidung'], level: 'a12' }),
  c('kl-teuer', 'teuer', 'caro', { example: 'Der Mantel ist zu teuer.', tags: ['kleidung'], level: 'a12' }),
  c('kl-billig', 'billig', 'barato', { example: 'Das T-Shirt ist billig.', tags: ['kleidung'], level: 'a12' }),

  // ── Corpo & saúde (der Körper) ────────────────────────────────────
  c('kp-kopf', 'Kopf', 'cabeça', { artikel: 'der', plural: 'Köpfe', example: 'Mein Kopf tut weh.', tags: ['koerper'], level: 'a12' }),
  c('kp-auge', 'Auge', 'olho', { artikel: 'das', plural: 'Augen', example: 'Ihre Augen sind grün.', tags: ['koerper'], level: 'a12' }),
  c('kp-ohr', 'Ohr', 'orelha, ouvido', { artikel: 'das', plural: 'Ohren', example: 'Der Hase hat lange Ohren.', tags: ['koerper'], level: 'a12' }),
  c('kp-nase', 'Nase', 'nariz', { artikel: 'die', plural: 'Nasen', example: 'Meine Nase ist kalt.', tags: ['koerper'], level: 'a12' }),
  c('kp-mund', 'Mund', 'boca', { artikel: 'der', plural: 'Münder', example: 'Mach bitte den Mund auf!', tags: ['koerper'], level: 'a12' }),
  c('kp-arm', 'Arm', 'braço', { artikel: 'der', plural: 'Arme', example: 'Mein Arm tut weh.', tags: ['koerper'], level: 'a12' }),
  c('kp-hand', 'Hand', 'mão', { artikel: 'die', plural: 'Hände', example: 'Ich wasche mir die Hände.', tags: ['koerper'], level: 'a12' }),
  c('kp-bein', 'Bein', 'perna', { artikel: 'das', plural: 'Beine', example: 'Er hat lange Beine.', tags: ['koerper'], level: 'a12' }),
  c('kp-fuss', 'Fuß', 'pé', { artikel: 'der', plural: 'Füße', example: 'Mein Fuß tut weh.', tags: ['koerper'], level: 'a12' }),
  c('kp-bauch', 'Bauch', 'barriga', { artikel: 'der', plural: 'Bäuche', example: 'Ich habe Bauchschmerzen.', tags: ['koerper'], level: 'a12' }),
  c('kp-ruecken', 'Rücken', 'costas', { artikel: 'der', plural: 'Rücken', example: 'Mein Rücken tut weh.', tags: ['koerper'], level: 'a12' }),
  c('kp-schmerzen', 'Schmerzen', 'dores (Pl.; singular: der Schmerz)', { artikel: 'die', example: 'Ich habe Kopfschmerzen.', tags: ['koerper'], level: 'a12' }),
  c('kp-fieber', 'Fieber', 'febre', { artikel: 'das', example: 'Das Kind hat Fieber.', tags: ['koerper'], level: 'a12' }),
  c('kp-husten', 'Husten', 'tosse', { artikel: 'der', example: 'Ich habe Husten.', tags: ['koerper'], level: 'a12' }),
  c('kp-krank', 'krank', 'doente', { example: 'Ich bin heute krank.', tags: ['koerper'], level: 'a12' }),
  c('kp-gesund', 'gesund', 'saudável', { example: 'Obst ist gesund.', tags: ['koerper'], level: 'a12' }),

  // ── Clima & estações (das Wetter) ─────────────────────────────────
  c('wt-wetter', 'Wetter', 'tempo (clima)', { artikel: 'das', example: 'Wie ist das Wetter heute?', tags: ['wetter'], level: 'a12' }),
  c('wt-sonne', 'Sonne', 'sol', { artikel: 'die', example: 'Die Sonne scheint.', tags: ['wetter'], level: 'a12' }),
  c('wt-regen', 'Regen', 'chuva', { artikel: 'der', example: 'Ich mag den Regen nicht.', tags: ['wetter'], level: 'a12' }),
  c('wt-schnee', 'Schnee', 'neve', { artikel: 'der', example: 'Im Winter gibt es Schnee.', tags: ['wetter'], level: 'a12' }),
  c('wt-wind', 'Wind', 'vento', { artikel: 'der', plural: 'Winde', example: 'Der Wind ist stark.', tags: ['wetter'], level: 'a12' }),
  c('wt-wolke', 'Wolke', 'nuvem', { artikel: 'die', plural: 'Wolken', example: 'Am Himmel sind viele Wolken.', tags: ['wetter'], level: 'a12' }),
  c('wt-fruehling', 'Frühling', 'primavera', { artikel: 'der', example: 'Im Frühling ist es warm.', tags: ['wetter'], level: 'a12' }),
  c('wt-sommer', 'Sommer', 'verão', { artikel: 'der', example: 'Im Sommer schwimmen wir viel.', tags: ['wetter'], level: 'a12' }),
  c('wt-herbst', 'Herbst', 'outono', { artikel: 'der', example: 'Im Herbst regnet es oft.', tags: ['wetter'], level: 'a12' }),
  c('wt-winter', 'Winter', 'inverno', { artikel: 'der', example: 'Im Winter ist es kalt.', tags: ['wetter'], level: 'a12' }),
  c('wt-warm', 'warm', 'quente, morno', { example: 'Heute ist es warm.', tags: ['wetter'], level: 'a12' }),
  c('wt-kalt', 'kalt', 'frio', { example: 'Im Dezember ist es kalt.', tags: ['wetter'], level: 'a12' }),
  c('wt-heiss', 'heiß', 'muito quente', { example: 'Der Sommer in Brasilien ist heiß.', tags: ['wetter'], level: 'a12' }),
  c('wt-grad', 'Grad', 'grau (temperatura)', { artikel: 'der', plural: 'Grade', example: 'Es sind heute 30 Grad.', tags: ['wetter'], level: 'a12' }),
  c('wt-esregnet', 'es regnet', 'está chovendo', { example: 'Heute regnet es den ganzen Tag.', tags: ['wetter'], level: 'a12' }),

  // ── Dia a dia (der Alltag) ────────────────────────────────────────
  c('al-duschen', 'duschen', 'tomar banho (de chuveiro)', { example: 'Ich dusche jeden Morgen.', tags: ['alltag'], level: 'a12' }),
  c('al-arbeit', 'Arbeit', 'trabalho', { artikel: 'die', example: 'Ich fahre mit dem Bus zur Arbeit.', tags: ['alltag'], level: 'a12' }),
  c('al-pause', 'Pause', 'pausa, intervalo', { artikel: 'die', plural: 'Pausen', example: 'Wir machen eine Pause.', tags: ['alltag'], level: 'a12' }),
  c('al-feierabend', 'Feierabend', 'fim do expediente', { artikel: 'der', example: 'Um sechs habe ich Feierabend.', tags: ['alltag'], level: 'a12' }),
  c('al-muede', 'müde', 'cansado', { example: 'Ich bin heute sehr müde.', tags: ['alltag'], level: 'a12' }),
  c('al-frueh', 'früh', 'cedo', { example: 'Ich stehe früh auf.', tags: ['alltag'], level: 'a12' }),
  c('al-spaet', 'spät', 'tarde', { example: 'Es ist schon spät.', tags: ['alltag'], level: 'a12' }),
  c('al-termin', 'Termin', 'compromisso, horário marcado', { artikel: 'der', plural: 'Termine', example: 'Ich habe morgen einen Termin.', tags: ['alltag'], level: 'a12' }),
  c('al-kalender', 'Kalender', 'calendário, agenda', { artikel: 'der', plural: 'Kalender', example: 'Der Termin steht im Kalender.', tags: ['alltag'], level: 'a12' }),
  c('al-aufraeumen', 'aufräumen', 'arrumar (separável)', { example: 'Ich räume mein Zimmer auf.', tags: ['alltag'], level: 'a12' }),
  c('al-putzen', 'putzen', 'limpar', { example: 'Am Samstag putze ich die Wohnung.', tags: ['alltag'], level: 'a12' }),
  c('al-schluessel', 'Schlüssel', 'chave', { artikel: 'der', plural: 'Schlüssel', example: 'Wo ist mein Schlüssel?', tags: ['alltag'], level: 'a12' }),
  c('al-tasche', 'Tasche', 'bolsa, sacola', { artikel: 'die', plural: 'Taschen', example: 'Die Tasche ist schwer.', tags: ['alltag'], level: 'a12' }),

  // ── Adjetivos básicos (Adjektive) ─────────────────────────────────
  c('adj-gross', 'groß', 'grande; alto', { example: 'Der Bahnhof ist groß.', tags: ['adjektive'], level: 'a11' }),
  c('adj-klein', 'klein', 'pequeno', { example: 'Die Wohnung ist klein.', tags: ['adjektive'], level: 'a11' }),
  c('adj-gut', 'gut', 'bom', { example: 'Der Kaffee ist gut.', tags: ['adjektive'], level: 'a11' }),
  c('adj-schlecht', 'schlecht', 'ruim', { example: 'Das Wetter ist heute schlecht.', tags: ['adjektive'], level: 'a11' }),
  c('adj-schoen', 'schön', 'bonito, belo', { example: 'Die Stadt ist schön.', tags: ['adjektive'], level: 'a11' }),
  c('adj-haesslich', 'hässlich', 'feio', { example: 'Ich finde die Jacke hässlich.', tags: ['adjektive'], level: 'a11' }),
  c('adj-neu', 'neu', 'novo', { example: 'Mein Handy ist neu.', tags: ['adjektive'], level: 'a11' }),
  c('adj-alt', 'alt', 'velho; idoso', { example: 'Die Kirche ist sehr alt.', tags: ['adjektive'], level: 'a11' }),
  c('adj-jung', 'jung', 'jovem', { example: 'Der Lehrer ist noch jung.', tags: ['adjektive'], level: 'a11' }),
  c('adj-schnell', 'schnell', 'rápido', { example: 'Der Zug ist schnell.', tags: ['adjektive'], level: 'a11' }),
  c('adj-langsam', 'langsam', 'lento, devagar', { example: 'Sprechen Sie bitte langsam!', tags: ['adjektive'], level: 'a11' }),
  c('adj-einfach', 'einfach', 'fácil, simples', { example: 'Die Aufgabe ist einfach.', tags: ['adjektive'], level: 'a11' }),
  c('adj-schwierig', 'schwierig', 'difícil', { example: 'Deutsch ist nicht so schwierig.', tags: ['adjektive'], level: 'a11' }),
  c('adj-wichtig', 'wichtig', 'importante', { example: 'Die Prüfung ist sehr wichtig.', tags: ['adjektive'], level: 'a11' }),
  c('adj-richtig', 'richtig', 'certo, correto', { example: 'Die Antwort ist richtig.', tags: ['adjektive'], level: 'a11' }),
  c('adj-falsch', 'falsch', 'errado', { example: 'Der Satz ist falsch.', tags: ['adjektive'], level: 'a11' }),

  // ── Dias, meses & datas (Tage, Monate & Datum) ────────────────────
  c('zz-montag', 'Montag', 'segunda-feira', { artikel: 'der', plural: 'Montage', example: 'Am Montag arbeite ich.', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-dienstag', 'Dienstag', 'terça-feira', { artikel: 'der', plural: 'Dienstage', example: 'Am Dienstag habe ich Deutschunterricht.', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-mittwoch', 'Mittwoch', 'quarta-feira', { artikel: 'der', plural: 'Mittwoche', example: 'Mittwoch ist die Mitte der Woche.', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-donnerstag', 'Donnerstag', 'quinta-feira', { artikel: 'der', plural: 'Donnerstage', example: 'Am Donnerstag gehe ich schwimmen.', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-freitag', 'Freitag', 'sexta-feira', { artikel: 'der', plural: 'Freitage', example: 'Freitag ist mein Lieblingstag.', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-samstag', 'Samstag', 'sábado', { artikel: 'der', plural: 'Samstage', example: 'Am Samstag gehe ich zum Markt.', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-sonntag', 'Sonntag', 'domingo', { artikel: 'der', plural: 'Sonntage', example: 'Am Sonntag schlafe ich lange.', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-januar', 'Januar', 'janeiro', { artikel: 'der', example: 'Im Januar beginnt das Jahr.', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-juli', 'Juli', 'julho', { artikel: 'der', example: 'Im Juli ist Sommer in Deutschland.', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-dezember', 'Dezember', 'dezembro', { artikel: 'der', example: 'Im Dezember ist Weihnachten.', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-monat', 'Monat', 'mês', { artikel: 'der', plural: 'Monate', example: 'Das Jahr hat zwölf Monate.', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-jahr', 'Jahr', 'ano', { artikel: 'das', plural: 'Jahre', example: 'Nächstes Jahr reise ich nach Deutschland.', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-geburtstag', 'Geburtstag', 'aniversário', { artikel: 'der', plural: 'Geburtstage', example: 'Wann hast du Geburtstag?', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-heute-abend', 'heute Abend', 'hoje à noite', { example: 'Was machst du heute Abend?', tags: ['zahlen-zeit'], level: 'a11' }),
  c('zz-datum', 'Datum', 'data', { artikel: 'das', plural: 'Daten', example: 'Welches Datum haben wir heute?', tags: ['zahlen-zeit'], level: 'a11' }),

  // ── Comida & bebida — ampliação A1.2 ──────────────────────────────
  c('es-obst', 'Obst', 'fruta(s)', { artikel: 'das', example: 'Ich esse jeden Tag Obst.', tags: ['comida'], level: 'a12' }),
  c('es-gemuese', 'Gemüse', 'legumes, verduras', { artikel: 'das', example: 'Gemüse ist gesund.', tags: ['comida'], level: 'a12' }),
  c('es-kartoffel', 'Kartoffel', 'batata', { artikel: 'die', plural: 'Kartoffeln', example: 'Die Kartoffeln sind noch heiß.', tags: ['comida'], level: 'a12' }),
  c('es-reis', 'Reis', 'arroz', { artikel: 'der', example: 'In Brasilien essen wir viel Reis.', tags: ['comida'], level: 'a12' }),
  c('es-fleisch', 'Fleisch', 'carne', { artikel: 'das', example: 'Ich esse kein Fleisch.', tags: ['comida'], level: 'a12' }),
  c('es-fisch', 'Fisch', 'peixe', { artikel: 'der', plural: 'Fische', example: 'Der Fisch schmeckt sehr gut.', tags: ['comida'], level: 'a12' }),
  c('es-kuchen', 'Kuchen', 'bolo', { artikel: 'der', plural: 'Kuchen', example: 'Zum Geburtstag gibt es Kuchen.', tags: ['comida'], level: 'a12' }),
  c('es-bier', 'Bier', 'cerveja', { artikel: 'das', plural: 'Biere', example: 'Ein Bier, bitte!', tags: ['comida'], level: 'a12' }),
  c('es-wein', 'Wein', 'vinho', { artikel: 'der', plural: 'Weine', example: 'Der Wein kommt aus Portugal.', tags: ['comida'], level: 'a12' }),
  c('es-saft', 'Saft', 'suco', { artikel: 'der', plural: 'Säfte', example: 'Ich trinke ein Glas Saft.', tags: ['comida'], level: 'a12' }),
  c('es-speisekarte', 'Speisekarte', 'cardápio', { artikel: 'die', plural: 'Speisekarten', example: 'Die Speisekarte, bitte!', tags: ['comida'], level: 'a12' }),
  c('es-rechnung', 'Rechnung', 'conta (do restaurante)', { artikel: 'die', plural: 'Rechnungen', example: 'Die Rechnung, bitte!', tags: ['comida'], level: 'a12' }),
  c('es-bestellen', 'bestellen', 'pedir (comida)', { example: 'Wir bestellen zwei Kaffee.', tags: ['comida'], level: 'a12' }),
  c('es-lecker', 'lecker', 'gostoso, delicioso', { example: 'Die Pizza ist lecker!', tags: ['comida'], level: 'a12' }),

  // ── Frases feitas — ampliação ─────────────────────────────────────
  c('fr-ichhaettegern', 'Ich hätte gern…', 'Eu queria… (pedido educado)', { example: 'Ich hätte gern einen Kaffee.', tags: ['frases'], level: 'a12' }),
  c('fr-zahlenbitte', 'Zahlen, bitte!', 'A conta, por favor!', { tags: ['frases'], level: 'a12' }),
  c('fr-gutebesserung', 'Gute Besserung!', 'Melhoras!', { tags: ['frases'], level: 'a12' }),
  c('fr-gutenappetit', 'Guten Appetit!', 'Bom apetite!', { tags: ['frases'], level: 'a11' }),
  c('fr-vielglueck', 'Viel Glück!', 'Boa sorte!', { tags: ['frases'], level: 'a11' }),
  c('fr-glueckwunsch', 'Herzlichen Glückwunsch!', 'Parabéns!', { example: 'Herzlichen Glückwunsch zum Geburtstag!', tags: ['frases'], level: 'a11' }),
  c('fr-verstehenicht', 'Ich verstehe nicht.', 'Eu não entendo.', { tags: ['frases'], level: 'a11' }),
  c('fr-wiederholen', 'Können Sie das wiederholen?', 'Pode repetir? (formal)', { tags: ['frases'], level: 'a11' }),
]

export const VOCAB_TAGS = [
  { tag: 'lugares', label: 'Lugares da cidade' },
  { tag: 'transporte', label: 'Transporte' },
  { tag: 'cores', label: 'Cores' },
  { tag: 'familia', label: 'Família' },
  { tag: 'comida', label: 'Comida & bebida' },
  { tag: 'tempo', label: 'Tempo & rotina' },
  { tag: 'apresentacao', label: 'Apresentação' },
  { tag: 'verbos', label: 'Verbos' },
  { tag: 'frases', label: 'Frases feitas' },
  { tag: 'gramatica', label: 'Palavras gramaticais' },
  { tag: 'berufe', label: 'Profissões' },
  { tag: 'laender', label: 'Países & línguas' },
  { tag: 'hobbys', label: 'Hobbys & lazer' },
  { tag: 'wohnung', label: 'Casa & móveis' },
  { tag: 'kleidung', label: 'Roupas' },
  { tag: 'koerper', label: 'Corpo & saúde' },
  { tag: 'wetter', label: 'Clima & estações' },
  { tag: 'alltag', label: 'Dia a dia' },
  { tag: 'adjektive', label: 'Adjetivos' },
  { tag: 'zahlen-zeit', label: 'Dias, meses & datas' },
] as const
